// src/components/input/_input.vue
<script lang="tsx">
import { defineComponent, PropType } from 'vue';
import BCMSIcon from '../icon.vue';

const component = defineComponent({
  props: {
    class: String,
    label: String,
    invalidText: String,
    helperText: String,
    onClick: Function as PropType<() => void>,
  },
  setup(props, ctx) {
    return () => {
      return (
        <label
          // for={props.label}
          class={`_bcmsInput ${props.class}`}
          onClick={() => {
            if (props.onClick) {
              props.onClick();
            }
          }}
        >
          {props.label ? (
            <span class="_bcmsInput--label">{props.label}</span>
          ) : (
            ''
          )}
          <span
            class={`_bcmsInput--inner ${
              props.invalidText ? '_bcmsInput--inner_invalid' : ''
            }`}
          >
            {ctx.slots.default ? ctx.slots.default() : ''}
            {props.invalidText ? (
              <div class="_bcmsInput--errorIcon" v-tooltip={props.invalidText}>
                <span class="_bcmsInput--tooltip">
                  <BCMSIcon src="/alert-triangle" />
                </span>
              </div>
            ) : (
              ''
            )}
          </span>
          {props.helperText ? (
            <span class="_bcmsInput--helperText" v-html={props.helperText} />
          ) : (
            ''
          )}
        </label>
      );
    };
  },
});
export default component;
</script>

// src/components/input/_input.svelte
<script lang="ts">
  import { beforeUpdate } from 'svelte';

  import { TooltipService } from '../../services';
  import { AlertTriangleIcon } from '../icons';

  export { className as class };
  export let id: string = undefined;
  export let label: string = undefined;
  export let invalidText: string = undefined;
  export let helperText: string = undefined;

  const buffer = {
    invalidText: '' + invalidText,
  };
  let className = '';
  let tooltip = TooltipService.bind(invalidText);

  beforeUpdate(() => {
    if (invalidText !== buffer.invalidText) {
      buffer.invalidText = '' + invalidText;
      tooltip = TooltipService.bind(invalidText);
    }
  });
</script>

<label for={label ? label : id} class="_bcmsInput {className}" on:click>
  {#if label}<span class="_bcmsInput--label">{label}</span>{/if}
  <span
    class="_bcmsInput--inner {invalidText ? '_bcmsInput--inner_invalid' : ''}">
    <slot />
    {#if invalidText}
      <div class="_bcmsInput--errorIcon">
        <span class="_bcmsInput--tooltip" use:tooltip>
          <AlertTriangleIcon />
        </span>
      </div>
    {/if}
  </span>
  {#if helperText}<span class="_bcmsInput--helperText">{@html helperText}</span>{/if}
</label>
