// src/components/input/date.svelte
<script lang="ts">
  import InputWrapper from './_input.svelte';
  import { beforeUpdate, createEventDispatcher } from 'svelte';
  import { CloseIcon } from '../icons';
  import {cy} from '../../services';

  export { className as class };
  export let value: string | number;
  export let label = '';
  export let invalidText = '';
  export let disabled: boolean = false;
  export let includeTime: boolean = false;
  export let helperText: string = undefined;
  export let cyTag: string = undefined;

  const dispatch = createEventDispatcher();

  let date = new Date(value);
  let dateString = `${date.getFullYear()}-${
    date.getMonth() + 1 < 10 ? '0' + (date.getMonth() + 1) : date.getMonth() + 1
  }-${date.getDate() < 10 ? '0' + date.getDate() : date.getDate()}`;
  let className = '';
  let buffer = {
    value: '' + value,
  };

  function handlerInput(event: Event) {
    const element = event.target as HTMLInputElement;
    dispatch('input', !element.valueAsNumber ? 0 : element.valueAsNumber);
    if ((event as KeyboardEvent).key === 'Enter') {
      dispatch('enter');
    }
  }

  beforeUpdate(() => {
    if (buffer.value !== value) {
      buffer.value = '' + value;
      date = new Date(value);
      dateString = `${date.getFullYear()}-${
        date.getMonth() + 1 < 10
          ? '0' + (date.getMonth() + 1)
          : date.getMonth() + 1
      }-${date.getDate() < 10 ? '0' + date.getDate() : date.getDate()}`;
    }
  });
</script>

<InputWrapper class={className} {label} {invalidText} {helperText}>
  <div use:cy={cyTag} class="_bcmsInput--date {includeTime ? '_bcmsInput--date_time' : ''}">
    <div class="_bcmsInput--date-wrapper">
      <input
        class="_bcmsInput--text date"
        {disabled}
        type="date"
        value={dateString}
        on:change={(event) => {
          handlerInput(event);
        }}
        on:keyup={(event) => {
          handlerInput(event);
        }} />
      <button
        aria-label="Reset date"
        title="Reset date"
        class="_bcmsInput--date-reset"
        on:click={() => {
          dispatch('input', 0);
        }}>
        <CloseIcon />
      </button>
    </div>
    {#if includeTime}
      <div class="_bcmsInput--date-wrapper">
        <input class="_bcmsInput--text time" {disabled} type="time" />
        <button
          aria-label="Reset date"
          title="Reset date"
          class="_bcmsInput--date-reset">
          <CloseIcon />
        </button>
      </div>
    {/if}
  </div>
</InputWrapper>

// src/components/input/date.vue
<script lang="tsx">
import { computed, defineComponent } from 'vue';
import { DefaultComponentProps } from '../_default';
import InputWrapper from './_input.vue';
import BCMSIcon from '../icon.vue';

const component = defineComponent({
  props: {
    ...DefaultComponentProps,
    value: {
      type: Number,
      required: true,
    },
    label: {
      type: String,
      default: '',
    },
    invalidText: {
      type: String,
      default: '',
    },
    disabled: {
      type: Boolean,
      default: false,
    },
    includeTime: {
      type: Boolean,
      default: false,
    },
    helperText: {
      type: String,
      default: '',
    },
  },
  emits: {
    input: (_value: number) => {
      return true;
    },
    enter: () => {
      return true;
    },
  },
  setup(props, ctx) {
    const dateAsString = computed(() => {
      return props.value ? toDate(props.value) : toDate(0);
    });

    function toDate(millis: number): string {
      const date = new Date(millis);
      return `${date.getFullYear()}-${
        date.getMonth() + 1 < 10
          ? '0' + (date.getMonth() + 1)
          : date.getMonth() + 1
      }-${date.getDate() < 10 ? '0' + date.getDate() : date.getDate()}`;
    }
    function handlerInput(event: Event) {
      const element = event.target as HTMLInputElement;
      const value = !element.valueAsNumber ? 0 : element.valueAsNumber;
      ctx.emit('input', value);
      if ((event as KeyboardEvent).key === 'Enter') {
        ctx.emit('enter');
      }
    }

    return () => (
      <InputWrapper
        class={props.class}
        label={props.label}
        invalidText={props.invalidText}
        helperText={props.helperText}
      >
        <div
          v-cy={props.cyTag}
          class={`_bcmsInput--date ${
            props.includeTime ? '_bcmsInput--date_time' : ''
          }`}
        >
          <div class="_bcmsInput--date-wrapper">
            <input
              id={props.label}
              class="_bcmsInput--text date"
              type="date"
              value={dateAsString.value}
              disabled={props.disabled}
              onChange={(event) => {
                handlerInput(event);
              }}
              onKeyup={(event) => {
                handlerInput(event);
              }}
            />
            <button
              aria-label="Reset date"
              title="Reset date"
              class="_bcmsInput--date-reset"
              disabled={props.disabled}
              onClick={() => {
                ctx.emit('input', 0);
              }}
            >
              <BCMSIcon src="/close" />
            </button>
          </div>
          {props.includeTime ? (
            <div class="_bcmsInput--date-wrapper">
              <input
                class="_bcmsInput--text time"
                disabled={props.disabled}
                type="time"
              />
              <button
                aria-label="Reset date"
                title="Reset date"
                disabled={props.disabled}
                class="_bcmsInput--date-reset"
              >
                <BCMSIcon src="/close" />
              </button>
            </div>
          ) : (
            ''
          )}
        </div>
      </InputWrapper>
    );
  },
});
export default component;
</script>
