// src/components/input/date.svelte
<script lang="ts">
  import InputWrapper from './_input.svelte';
  import { beforeUpdate, createEventDispatcher } from 'svelte';
  import { CloseIcon } from '../icons';
  import {cy} from '../../services';

  export { className as class };
  export let value: string | number;
  export let label = '';
  export let invalidText = '';
  export let disabled: boolean = false;
  export let includeTime: boolean = false;
  export let helperText: string = undefined;
  export let cyTag: string = undefined;

  const dispatch = createEventDispatcher();

  let date = new Date(value);
  let dateString = `${date.getFullYear()}-${
    date.getMonth() + 1 < 10 ? '0' + (date.getMonth() + 1) : date.getMonth() + 1
  }-${date.getDate() < 10 ? '0' + date.getDate() : date.getDate()}`;
  let className = '';
  let buffer = {
    value: '' + value,
  };

  function handlerInput(event: Event) {
    const element = event.target as HTMLInputElement;
    dispatch('input', !element.valueAsNumber ? 0 : element.valueAsNumber);
    if ((event as KeyboardEvent).key === 'Enter') {
      dispatch('enter');
    }
  }

  beforeUpdate(() => {
    if (buffer.value !== value) {
      buffer.value = '' + value;
      date = new Date(value);
      dateString = `${date.getFullYear()}-${
        date.getMonth() + 1 < 10
          ? '0' + (date.getMonth() + 1)
          : date.getMonth() + 1
      }-${date.getDate() < 10 ? '0' + date.getDate() : date.getDate()}`;
    }
  });
</script>

<InputWrapper class={className} {label} {invalidText} {helperText}>
  <div use:cy={cyTag} class="_bcmsInput--date {includeTime ? '_bcmsInput--date_time' : ''}">
    <div class="_bcmsInput--date-wrapper">
      <input
        class="_bcmsInput--text date"
        {disabled}
        type="date"
        value={dateString}
        on:change={(event) => {
          handlerInput(event);
        }}
        on:keyup={(event) => {
          handlerInput(event);
        }} />
      <button
        aria-label="Reset date"
        title="Reset date"
        class="_bcmsInput--date-reset"
        on:click={() => {
          dispatch('input', 0);
        }}>
        <CloseIcon />
      </button>
    </div>
    {#if includeTime}
      <div class="_bcmsInput--date-wrapper">
        <input class="_bcmsInput--text time" {disabled} type="time" />
        <button
          aria-label="Reset date"
          title="Reset date"
          class="_bcmsInput--date-reset">
          <CloseIcon />
        </button>
      </div>
    {/if}
  </div>
</InputWrapper>

// src/components/input/date.tsx
import { computed, defineComponent } from 'vue';
import { DefaultComponentProps } from '../_default';
import InputWrapper from './_input';
import BCMSIcon from '../icon';

const component = defineComponent({
  props: {
    ...DefaultComponentProps,
    value: {
      type: Number,
      required: true,
    },
    label: {
      type: String,
      default: '',
    },
    invalidText: {
      type: String,
      default: '',
    },
    disabled: {
      type: Boolean,
      default: false,
    },
    includeTime: {
      type: Boolean,
      default: false,
    },
    helperText: {
      type: String,
      default: '',
    },
  },
  emits: {
    input: (_value: number) => {
      return true;
    },
    enter: () => {
      return true;
    },
  },
  setup(props, ctx) {
    const dateAsString = computed(() => {
      return props.value ? toDate(props.value) : toDate(0);
    });

    function toDate(millis: number): string {
      const date = new Date(millis);
      return `${date.getFullYear()}-${
        date.getMonth() + 1 < 10
          ? '0' + (date.getMonth() + 1)
          : date.getMonth() + 1
      }-${date.getDate() < 10 ? '0' + date.getDate() : date.getDate()}`;
    }
    function handlerInput(event: Event) {
      const element = event.target as HTMLInputElement;
      const value = !element.valueAsNumber ? 0 : element.valueAsNumber;
      ctx.emit('input', value);
      if ((event as KeyboardEvent).key === 'Enter') {
        ctx.emit('enter');
      }
    }

    return () => (
      <InputWrapper
        class={props.class}
        label={props.label}
        invalidText={props.invalidText}
        helperText={props.helperText}
      >
        <div
          v-cy={props.cyTag}
          class={`_bcmsInput--date items-center ${
            props.includeTime ? 'block sm:flex' : 'flex'
          }`}
        >
          <div
            class={`relative flex items-center justify-center ${
              props.includeTime
                ? 'w-full border border-r border-grey border-opacity-100 rounded-3.5 mb-2.5 hover:border-opacity-50 focus-within:border-opacity-50 transition-colors duration-300 sm:mb-0 sm:rounded-r-none sm:w-2/3'
                : 'w-full'
            }`}
          >
            <input
              id={props.label}
              class={`date relative block w-full bg-white border transition-all duration-300 shadow-none font-normal not-italic text-base leading-tight -tracking-0.01 text-dark h-11 py-0 px-4.5 outline-none placeholder-grey placeholder-opacity-100 pt-3 pb-[9px] pl-4.5 resize-none top-0 left-0 overflow-hidden hover:shadow-input focus-within:shadow-input ${
                props.invalidText
                  ? 'border-red hover:border-red focus-within:border-red'
                  : 'border-grey hover:border-grey hover:border-opacity-50 focus-within:border-grey focus-within:border-opacity-50'
              } ${!props.includeTime && props.invalidText ? 'pr-11' : 'pr-2'} ${
                props.disabled
                  ? 'cursor-not-allowed opacity-40 shadow-none border-grey'
                  : 'cursor-auto'
              } ${
                props.includeTime
                  ? 'border-none rounded-3.5 sm:rounded-r-none'
                  : 'rounded-3.5'
              } dark:bg-darkGrey dark:text-light`}
              type="date"
              value={dateAsString.value}
              disabled={props.disabled}
              onChange={(event) => {
                handlerInput(event);
              }}
              onKeyup={(event) => {
                handlerInput(event);
              }}
            />
            <button
              aria-label="Reset date"
              title="Reset date"
              class="group absolute top-2.5 right-[5px] bg-white flex z-10 dark:bg-darkGrey"
              disabled={props.disabled}
              onClick={() => {
                ctx.emit('input', 0);
              }}
            >
              <BCMSIcon
                src="/close"
                class="text-dark text-opacity-50 fill-current w-6 h-6 m-auto transition-all duration-200 group-hover:text-red group-hover:text-opacity-100 group-focus:text-red group-focus:text-opacity-100 dark:text-light"
              />
            </button>
          </div>
          {props.includeTime ? (
            <div
              class={`relative flex items-center justify-center ${
                props.includeTime
                  ? 'w-full border border-r border-grey border-opacity-100 rounded-3.5 hover:border-opacity-50 focus-within:border-opacity-50 transition-colors duration-300 sm:rounded-l-none sm:w-1/3'
                  : 'w-full'
              }`}
            >
              <input
                class={`time relative block w-full bg-white border transition-all duration-300 shadow-none font-normal not-italic text-base leading-tight -tracking-0.01 text-dark h-11 py-0 px-4.5 outline-none placeholder-grey placeholder-opacity-100 pt-3 pb-[9px] pl-4.5 resize-none top-0 left-0 overflow-hidden sm:pl-2 hover:shadow-input focus-within:shadow-input ${
                  props.invalidText
                    ? 'border-red hover:border-red focus-within:border-red'
                    : 'border-grey hover:border-grey hover:border-opacity-50 focus-within:border-grey focus-within:border-opacity-50'
                } ${
                  props.includeTime && props.invalidText ? 'pr-11' : 'pr-2'
                } ${
                  props.disabled
                    ? 'cursor-not-allowed opacity-40 shadow-none border-grey'
                    : 'cursor-auto'
                } ${
                  props.includeTime
                    ? 'border-none rounded-3.5 sm:rounded-l-none'
                    : 'rounded-3.5'
                }`}
                disabled={props.disabled}
                type="time"
              />
              <button
                aria-label="Reset date"
                title="Reset date"
                disabled={props.disabled}
                class="group absolute top-2.5 right-[5px] bg-white flex z-10"
              >
                <BCMSIcon
                  src="/close"
                  class="text-dark text-opacity-50 fill-current w-6 h-6 m-auto transition-all duration-200 group-hover:text-red group-hover:text-opacity-100 group-focus:text-red group-focus:text-opacity-100"
                />
              </button>
            </div>
          ) : (
            ''
          )}
        </div>
      </InputWrapper>
    );
  },
});
export default component;
