// src/components/input/markdown.vue
<script lang="tsx">
import { defineComponent } from 'vue';
import { DefaultComponentProps } from '../_default';
import InputWrapper from './_input.vue';

const component = defineComponent({
  props: {
    ...DefaultComponentProps,
    value: String,
    modelValue: String,
    placeholder: String,
    label: String,
    invalidText: String,
    helperText: String,
    disabled: Boolean,
  },
  emits: {
    input: (_value: string) => {
      return true;
    },
    'update:modelValue': (_value: string) => {
      return true;
    },
  },
  setup(props, ctx) {
    function handleInput(event: Event) {
      const el = event.target as HTMLInputElement;
      if (!el) {
        return;
      }
      ctx.emit('input', el.value);
      ctx.emit('update:modelValue', el.value);
    }

    return () => (
      <InputWrapper
        class={props.class}
        label={props.label}
        invalidText={props.invalidText}
        helperText={props.helperText}
      >
        <div
          class={`_bcmsInput--markdown ${
            props.disabled ? '_bcmsInput--markdown_disabled' : ''
          }`}
        >
          <textarea
            rows={3}
            placeholder={props.placeholder}
            value={props.modelValue ? props.modelValue : props.value}
            id={props.label}
            onKeyup={handleInput}
            onChange={handleInput}
            class="_bcmsInput--textarea"
          />
        </div>
      </InputWrapper>
    );
  },
});
export default component;
</script>

// src/components/input/markdown.svelte
<script lang="ts">
  import InputWrapper from './_input.svelte';
  import { createEventDispatcher } from 'svelte';
  import * as uuid from 'uuid';

  export { className as class };
  export let value = '';
  export let placeholder = '';
  export let label = '';
  export let invalidText = '';
  export let disabled = false;
  export let helperText: string = undefined;

  const inputId = uuid.v4();
  const dispatch = createEventDispatcher();
  let className = '';

  function handleInput(event: Event) {
    const el = event.target as HTMLInputElement;
    dispatch('input', el.value);
  }
  // onMount(() => {
  //   // smd = new SimpleMDE({
  //   //   element: document.getElementById(areaId),
  //   //   initialValue: '' + value,
  //   //   placeholder,
  //   //   toolbar: [
  //   //     'bold',
  //   //     'italic',
  //   //     'heading',
  //   //     '|',
  //   //     'unordered-list',
  //   //     'ordered-list',
  //   //     '|',
  //   //     'preview',
  //   //   ],
  //   //   renderingConfig: {
  //   //     codeSyntaxHighlighting: true,
  //   //   },
  //   //   status: [
  //   //     {
  //   //       className: 'keystrokes',
  //   //       defaultValue: () => {},
  //   //       onUpdate: () => {
  //   //         if (smd) {
  //   //           dispatch('input', smd.value());
  //   //         }
  //   //       },
  //   //     },
  //   //   ],
  //   // });
  // });
</script>

<InputWrapper id={inputId} class={className} {label} {invalidText} {helperText}>
  <div
    class="_bcmsInput--markdown {disabled
      ? '_bcmsInput--markdown_disabled'
      : ''}"
  >
    <textarea
      rows="3"
      {placeholder}
      {value}
      id={label ? label : inputId}
      on:keyup={handleInput}
      on:change={handleInput}
    />
  </div>
</InputWrapper>
