// src/components/input/number.svelte
<script lang="ts">
  import InputWrapper from './_input.svelte';
  import { createEventDispatcher } from 'svelte';

  export { className as class };
  export let value = 0;
  export let placeholder = '';
  export let label = '';
  export let invalidText = '';
  export let disabled = false;
  export let helperText: string = undefined;

  const dispatch = createEventDispatcher();
  let className = '';

  function handleInput(event: Event) {
    const element = event.target as HTMLInputElement;
    if (!element) {
      return;
    }
    if (!isNaN(element.valueAsNumber)) {
      dispatch('input', element.valueAsNumber);
    } else {
      if (element.value !== '') {
        element.valueAsNumber = value;
      }
    }
    if ((event as KeyboardEvent).key === 'Enter') {
      dispatch('enter');
    }
  }
</script>

<InputWrapper class={className} {label} {invalidText} {helperText}>
  <input
    id={label}
    class="_bcmsInput--text"
    type="number"
    {placeholder}
    step="0.00000001"
    value={`${value}`}
    {disabled}
    on:change={handleInput}
    on:keyup={handleInput} />
</InputWrapper>

// src/components/input/number.vue
<script lang="tsx">
import { defineComponent } from 'vue';
import InputWrapper from './_input.vue';

const component = defineComponent({
  inheritAttrs: true,
  props: {
    class: String,
    value: Number,
    modelValue: Number,
    placeholder: String,
    label: String,
    invalidText: String,
    disabled: Boolean,
    helperText: String,
  },
  emits: {
    enter: () => {
      return true;
    },
    input: (_: number) => {
      return true;
    },
    'update:modelValue': (_: number) => {
      return true;
    },
  },
  setup(props, ctx) {
    function inputHandler(event: Event) {
      const element = event.target as HTMLInputElement;
      if (!element) {
        return;
      }
      let val = element.value.replace(/[^0-9.-.]+/g, '');
      const dotParts = val.split('.');
      if (dotParts.length > 2) {
        val = dotParts.slice(0, 2).join('.');
      }
      element.value = val;
      const output = parseFloat(val);
      if (isNaN(output)) {
        ctx.emit('update:modelValue', 0);
        ctx.emit('input', 0);
      } else {
        ctx.emit('update:modelValue', output);
        ctx.emit('input', output);
      }
    }

    return () => {
      return (
        <InputWrapper
          class={props.class}
          label={props.label}
          helperText={props.helperText}
          invalidText={props.invalidText}
        >
          <input
            id={props.label}
            class="_bcmsInput--text"
            placeholder={props.placeholder}
            value={props.value ? props.value : props.modelValue}
            disabled={props.disabled}
            onChange={inputHandler}
            onKeyup={(event) => {
              inputHandler(event);
              if (event.key === 'Enter') {
                ctx.emit('enter');
              }
            }}
          />
        </InputWrapper>
      );
    };
  },
});
export default component;
</script>
