// src/components/input/password.svelte
<script lang="ts">
  import InputWrapper from './_input.svelte';
  import { createEventDispatcher } from 'svelte';
  import { EyeHideIcon, EyeShowIcon } from '../icons';
  import { cy } from '../../services';

  export { className as class };
  export let value = '';
  export let placeholder = '';
  export let label = '';
  export let invalidText = '';
  export let disabled = false;
  export let helperText: string = undefined;
  export let cyTag: string = undefined;

  const dispatch = createEventDispatcher();
  let className = '';
  let show: boolean = false;

  function inputHandler(event: Event) {
    const element = event.target as HTMLInputElement;

    if (!element) return;

    dispatch('input', element.value);
  }
</script>

<InputWrapper class={className} {label} {invalidText} {helperText}>
  <div use:cy={cyTag} class="_bcmsInput--password">
    <input
      id={label}
      class="_bcmsInput--text"
      {placeholder}
      {value}
      type={show ? 'text' : 'password'}
      {disabled}
      on:change={inputHandler}
      on:keyup={(event) => {
        inputHandler(event);
        if (event.key === 'Enter') {
          dispatch('enter');
        }
      }} />
    <button
      class="_bcmsInput--password-toggle"
      type="button"
      {disabled}
      on:click={() => {
        show = !show;
      }}>
      {#if show}
        <EyeShowIcon />
      {:else}
        <EyeHideIcon class="hide" />
      {/if}
    </button>
  </div>
</InputWrapper>

// src/components/input/password.vue
<script lang="tsx">
import { defineComponent, ref } from 'vue';
import BCMSIcon from '../icon.vue';
import InputWrapper from './_input.vue';

const component = defineComponent({
  props: {
    class: String,
    value: String,
    modelValue: String,
    placeholder: String,
    label: String,
    invalidText: String,
    disabled: Boolean,
    helperText: String,
  },
  emits: {
    input: (value: string) => {
      return value;
    },
    enter: (_?: unknown) => {
      return _;
    },
    'update:modelValue': (value: string) => {
      return value;
    },
  },
  setup(props, ctx) {
    const showRef = ref(false);
    function inputHandler(event: Event) {
      const element = event.target as HTMLInputElement;
      if (!element) return;
      ctx.emit('update:modelValue', element.value);
      ctx.emit('input', element.value);
    }
    return () => {
      return (
        <InputWrapper
          class={props.class}
          label={props.label}
          invalidText={props.invalidText}
          helperText={props.helperText}
        >
          <div class="_bcmsInput--password">
            <input
              id={props.label}
              class="_bcmsInput--text"
              placeholder={props.placeholder}
              value={props.value ? props.value : props.modelValue}
              type={showRef.value ? 'text' : 'password'}
              disabled={props.disabled}
              onChange={inputHandler}
              onKeyup={(event) => {
                inputHandler(event);
                if (event.key === 'Enter' && props.onEnter) {
                  props.onEnter();
                }
              }}
            />
            <button
              class="_bcmsInput--password-toggle"
              type="button"
              disabled={props.disabled}
              onClick={() => {
                showRef.value = !showRef.value;
              }}
            >
              {showRef.value ? (
                <BCMSIcon src="/eye/show" />
              ) : (
                <BCMSIcon src="/eye/hide" />
              )}
            </button>
          </div>
        </InputWrapper>
      );
    };
  },
});
export default component;
</script>
