// src/components/input/text.vue
<script lang="tsx">
import { defineComponent, PropType } from 'vue';
import InputWrapper from './_input.vue';

const component = defineComponent({
  inheritAttrs: true,
  props: {
    class: String,
    value: String,
    modelValue: String,
    placeholder: String,
    label: String,
    invalidText: String,
    disabled: Boolean,
    helperText: String,
    onInput: Function as PropType<(value: string) => void>,
    onEnter: Function as PropType<() => void>,
  },
  emits: {
    enter: () => {
      return true;
    },
    input: (_: string) => {
      return true;
    },
    'update:modelValue': (_: string) => {
      return true;
    },
  },
  setup(props, ctx) {
    function inputHandler(event: Event) {
      const element = event.target as HTMLInputElement;
      if (!element) {
        return;
      }
      ctx.emit('update:modelValue', element.value);
      ctx.emit('input', element.value);
    }
    return () => {
      return (
        <InputWrapper
          class={props.class}
          label={props.label}
          helperText={props.helperText}
          invalidText={props.invalidText}
        >
          <input
            id={props.label}
            class="_bcmsInput--text"
            placeholder={props.placeholder}
            value={props.value ? props.value : props.modelValue}
            disabled={props.disabled}
            onChange={inputHandler}
            onKeyup={(event) => {
              inputHandler(event);
              if (event.key === 'Enter') {
                ctx.emit('enter');
              }
            }}
          />
        </InputWrapper>
      );
    };
  },
});
export default component;
</script>

// src/components/input/text.svelte
<script lang="ts">
  import * as uuid from 'uuid';
  import { createEventDispatcher } from 'svelte';
  import InputWrapper from './_input.svelte';
  import { cy } from '../../services';

  export { className as class };
  export let value = '';
  export let placeholder = '';
  export let label = '';
  export let invalidText = '';
  export let disabled = false;
  export let helperText: string = undefined;
  export let cyTag: string = undefined;

  const inputId = uuid.v4();
  const dispatch = createEventDispatcher();
  let className = '';

  function inputHandler(event: Event) {
    const element = event.target as HTMLInputElement;
    if (!element) {
      return;
    }
    dispatch('input', element.value);
  }
</script>

<InputWrapper id={inputId} class={className} {label} {invalidText} {helperText}>
  <input
    use:cy={cyTag}
    id={label ? label : inputId}
    class="_bcmsInput--text"
    {placeholder}
    {value}
    {disabled}
    on:change={inputHandler}
    on:keyup={(event) => {
      inputHandler(event);
      if (event.key === 'Enter') {
        dispatch('enter');
      }
    }} />
</InputWrapper>
