// src/components/input/text-area.vue
<script lang="tsx">
import { defineComponent, PropType, ref } from 'vue';
import InputWrapper from './_input.vue';

const component = defineComponent({
  props: {
    class: {
      type: String,
      default: '',
    },
    modelValue: String,
    value: {
      type: String,
      default: '',
    },
    placeholder: {
      type: String,
      default: '',
    },
    label: {
      type: String,
      default: '',
    },
    invalidText: {
      type: String,
      default: '',
    },
    helperText: {
      type: String,
      default: '',
    },
    disabled: {
      type: Boolean,
      default: false,
    },
    minHeight: {
      type: Number,
      default: 44,
    },
    onInput: Function as PropType<(value: string) => void>,
  },
  emits: {
    input: (value: string) => {
      return value;
    },
    'update:modelValue': (value?: string) => {
      return value;
    },
  },
  setup(props, ctx) {
    const height = ref(props.minHeight);
    const logic = {
      inputHandler(event: Event) {
        const element = event.target as HTMLTextAreaElement;
        if (!element) {
          return;
        }
        ctx.emit('input', element.value);
      },
      handleHeight(event: Event) {
        const element = event.target as HTMLInputElement;
        if (!element) {
          return;
        }
        height.value = Math.min(element.scrollHeight);
      },
    };

    return () => {
      return (
        <InputWrapper
          class={props.class}
          label={props.label}
          invalidText={props.invalidText}
          helperText={props.helperText}
        >
          <textarea
            class="_bcmsInput--textarea"
            onChange={logic.inputHandler}
            onInput={logic.handleHeight}
            placeholder={props.placeholder}
            value={props.value ? props.value : props.modelValue}
            disabled={props.disabled}
            style={`min-height: ${props.minHeight}px; height: ${height.value}px`}
          />
        </InputWrapper>
      );
    };
  },
});
export default component;
</script>

// src/components/input/text-area.svelte
<script lang="ts">
  import InputWrapper from './_input.svelte';
  import { createEventDispatcher } from 'svelte';

  export { className as class };
  export let value = '';
  export let placeholder = '';
  export let label = '';
  export let invalidText = '';
  export let disabled = false;
  export let minHeight = 44;

  const dispatch = createEventDispatcher();
  let className = '';
  let height = minHeight + 0;

  function inputHandler(event: Event) {
    const element = event.target as HTMLTextAreaElement;
    if (!element) {
      return;
    }
    dispatch('input', element.value);
  }
  function handleHeight(event: Event) {
    const element = event.target as HTMLInputElement;
    if (!element) {
      return;
    }
    height = Math.min(element.scrollHeight);
  }
</script>

<InputWrapper class={className} {label} {invalidText}>
  <textarea
    class="_bcmsInput--textarea"
    on:change={inputHandler}
    on:input={handleHeight}
    {placeholder}
    value={`${value}`}
    {disabled}
    style="min-height: {minHeight}px; height: {height}px" />
</InputWrapper>
