// src/components/input/toggle.vue
<script lang="tsx">
import { defineComponent, PropType, ref } from 'vue';
import { DefaultComponentProps } from '../_default';
import InputWrapper from './_input.vue';

const component = defineComponent({
  props: {
    ...DefaultComponentProps,
    label: String,
    modelValue: Boolean,
    value: {
      type: Boolean,
      default: false,
    },
    disabled: {
      type: Boolean,
      default: false,
    },
    states: Object as PropType<[string, string]>,
    helperText: String,
    onInput: Function as PropType<(value: boolean) => void | Promise<void>>,
  },
  emits: {
    input: (_value: boolean) => {
      return true;
    },
    'update:modelValue': (value?: boolean) => {
      return true;
    },
  },
  setup(props, ctx) {
    const state = ref(props.modelValue ? props.modelValue : props.value);

    function keyDownHandler(event: KeyboardEvent) {
      if (event.key === 'Enter') {
        ctx.emit('input', !state.value);
        ctx.emit('update:modelValue', !state.value);
      }
    }

    return () => (
      <InputWrapper
        class={`_bcmsInput--toggle_contentWidth ${props.class}`}
        label={props.label}
        helperText={props.helperText}
        onClick={() => {
          if (!props.disabled) {
            ctx.emit('input', !state.value);
            ctx.emit('update:modelValue', !state.value);
          }
        }}
      >
        <div
          id={props.label}
          class="_bcmsInput--toggle"
          tabindex="0"
          onKeydown={keyDownHandler}
        >
          <span
            class={`_bcmsInput--toggle-inner ${
              state.value ? '_bcmsInput--toggle-inner_checked' : ''
            } ${props.disabled ? '_bcmsInput--toggle-inner_disabled' : ''}`}
          >
            <span class="circle" />
            {props.states && props.states.length === 2 ? (
              <span class="_bcmsInput--toggle-state">
                {state.value ? props.states[0] : props.states[1]}
              </span>
            ) : (
              ''
            )}
          </span>
        </div>
      </InputWrapper>
    );
  },
});
export default component;
</script>

// src/components/input/toggle.svelte
<script lang="ts">
  import * as uuid from 'uuid';
  import { createEventDispatcher, beforeUpdate } from 'svelte';
  import InputWrapper from './_input.svelte';

  export { className as class };
  export let label: string = undefined;
  export let value: boolean = false;
  export let disabled: boolean = false;
  export let states: [string, string] = undefined;
  export let helperText: string = undefined;

  const inputId = uuid.v4();
  const dispatch = createEventDispatcher();
  let className = '';
  let state = value ? true : false;

  function keydownHandler(event: KeyboardEvent) {
    const element = event.target as HTMLDivElement;
    if (!element) {
      return;
    }

    if (event.key === 'Enter') {
      dispatch('input', !state);
    }
  }

  beforeUpdate(() => {
    state = value ? true : false;
  });
</script>

<InputWrapper
  id={inputId}
  class="_bcmsInput--toggle_contentWidth {className}"
  {label}
  {helperText}
  on:click={() => {
    if (!disabled) {
      dispatch('input', !state);
    }
  }}
>
  <div
    id={label ? label : inputId}
    class="_bcmsInput--toggle"
    tabindex="0"
    on:keydown={keydownHandler}
  >
    <span
      class="_bcmsInput--toggle-inner
        {state
        ? '_bcmsInput--toggle-inner_checked'
        : ''}
        {disabled ? '_bcmsInput--toggle-inner_disabled' : ''}"
    >
      <span class="circle" />
    </span>
    {#if states && states.length === 2}
      <span class="_bcmsInput--toggle-state"
        >{state ? states[0] : states[1]}</span
      >
    {/if}
  </div>
</InputWrapper>
