// src/components/modals/modal.svelte
<script lang="ts">
  import { createEventDispatcher, onDestroy } from 'svelte';
  import { fade } from 'svelte/transition';
  import { StoreService } from '../../services';
  import { CloseIcon } from '../icons';
  import Button from '../button.svelte';

  export { className as class };
  export let name: string;
  export let title: string = undefined;

  const animationTime = 300;
  const dispatch = createEventDispatcher();
  let show = false;
  let className = '';
  let closing = false;

  StoreService.create(name, show);
  const toggleUnsunscribe = StoreService.subscribe(name, async (value) => {
    await delay(20);
    if (typeof value === 'boolean') {
      if (show && !value) {
        closing = true;
        delay(animationTime).then(() => {
          closing = false;
          dispatch('animationDone');
        });
      }
      show = value;
    } else if (typeof value === 'object') {
      if (typeof value.show !== 'undefined') {
        if (show && !value.show) {
          closing = true;
          delay(animationTime).then(() => {
            closing = false;
            dispatch('animationDone');
          });
        }
        show = value.show;
      }
    }
  });

  async function delay(time: number) {
    return new Promise<void>((resolve) => {
      setTimeout(() => {
        resolve();
      }, time);
    });
  }
  function cancel() {
    dispatch('cancel');
  }
  function done() {
    dispatch('done');
  }

  onDestroy(() => {
    toggleUnsunscribe();
  });
</script>

{#if show}
  <div
    in:fade
    out:fade={{ duration: animationTime }}
    class="bcmsModal {className}">
    <div
      class="bcmsModal--overlay"
      tabindex="0"
      role="button"
      aria-label="Close modal"
      on:keydown={(event) => {
        if (event.key === 'Enter') {
          cancel();
        }
      }}
      on:click={() => {
        cancel();
      }} />
    <div class="bcmsModal--inner">
      <header class="bcmsModal--header mb-50">
        {#if $$slots.header}
          <slot name="header" />
        {:else if title}
          <div class="bcmsModal--title">{title}</div>
        {/if}
        <button
          disabled={closing}
          aria-label="Close modal"
          on:click={() => {
            cancel();
          }}
          class="bcmsModal--close">
          <CloseIcon />
        </button>
      </header>
      <div class="bcmsModal--body">
        <slot />
      </div>
      <div class="bcmsModal--actions">
        {#if $$slots.actions}
          <slot name="actions" />
        {:else}
          <Button disabled={closing} on:click={done}><span>Done</span></Button>
          <Button disabled={closing} kind="ghost" on:click={cancel}>
            Cancel
          </Button>
        {/if}
      </div>
    </div>
  </div>
{/if}

// src/components/modals/_modal.vue
<script lang="tsx">
import { defineComponent, PropType, Transition } from 'vue';
import { BCMSIcon, BCMSButton } from '../../components';

const component = defineComponent({
  props: {
    class: String,
    show: {
      type: Boolean,
      required: true,
    },
    title: String,
    actionName: String,
    beforeDone: Function as PropType<() => boolean>,
    onDone: Function as PropType<() => void>,
    onCancel: Function as PropType<() => void>,
    doNotShowFooter: Boolean,
  },
  emits: {
    done: (_?: unknown) => {
      return true;
    },
    cancel: (_?: unknown) => {
      return true;
    },
  },

  setup(props, ctx) {
    function cancel() {
      ctx.emit('cancel');
    }
    function done() {
      if (props.beforeDone) {
        if (!props.beforeDone()) {
          return;
        }
      }
      ctx.emit('done');
    }

    return () => {
      return (
        <Transition name="fade">
          {props.show && (
            <div class={`bcmsModal ${props.class ? props.class : ''}`}>
              <div
                class="bcmsModal--overlay"
                tabindex="0"
                role="button"
                aria-label="Close modal"
                onKeydown={(event) => {
                  if (event.key === 'Enter') {
                    cancel();
                  }
                }}
                onClick={() => {
                  cancel();
                }}
              />
              <div class="bcmsModal--inner">
                <header class="bcmsModal--header mb-50">
                  {ctx.slots.header ? (
                    ctx.slots.header()
                  ) : props.title ? (
                    <div class="bcmsModal--title">{props.title}</div>
                  ) : (
                    ''
                  )}
                  <button
                    aria-label="Close modal"
                    onClick={cancel}
                    class="bcmsModal--close"
                  >
                    <BCMSIcon src="/close" />
                  </button>
                </header>
                <div class="bcmsModal--body customScrollbar">
                  {ctx.slots.default ? ctx.slots.default() : ''}
                </div>
                {props.doNotShowFooter ? (
                  ''
                ) : (
                  <div class="bcmsModal--actions">
                    {ctx.slots.actions ? (
                      ctx.slots.actions()
                    ) : (
                      <>
                        <BCMSButton onClick={done}>
                          <span>
                            {props.actionName ? props.actionName : 'Done'}
                          </span>
                        </BCMSButton>
                        <BCMSButton kind="ghost" onClick={cancel}>
                          Cancel
                        </BCMSButton>
                      </>
                    )}
                  </div>
                )}
              </div>
            </div>
          )}
        </Transition>
      );
    };
  },
});
export default component;
</script>
