// src/components/modals/media/picker.vue
<script lang="tsx">
import { defineComponent, ref } from 'vue';
import type { BCMSMedia } from '@becomes/cms-sdk/types';
import {
  BCMSMediaPickerModalInputData,
  BCMSMediaPickerModalOutputData,
  BCMSModalServiceItemInputDefaults,
} from '../../../types';
import Modal from '../_modal.vue';
import { BCMSMediaViewer } from '../../media';

interface Data
  extends BCMSModalServiceItemInputDefaults<BCMSMediaPickerModalOutputData> {
  media?: BCMSMedia;
}

const component = defineComponent({
  setup() {
    const show = ref(false);
    const modalData = ref(getData());

    window.bcms.services.modal.media.picker = {
      hide() {
        show.value = false;
      },
      show(data) {
        modalData.value = getData(data);
        show.value = true;
      },
    };

    function getData(inputData?: BCMSMediaPickerModalInputData): Data {
      const d: Data = {
        title: 'Media picker',
      };
      if (inputData) {
        if (inputData.title) {
          d.title = inputData.title;
        }
        if (inputData.onDone) {
          d.onDone = inputData.onDone;
        }
        if (inputData.onCancel) {
          d.onCancel = inputData.onCancel;
        }
        if (inputData.media) {
          d.media = inputData.media;
        }
      }
      return d;
    }
    function cancel() {
      if (modalData.value.onCancel) {
        const result = modalData.value.onCancel();
        if (result instanceof Promise) {
          result.catch((error) => {
            console.error(error);
          });
        }
      }
      window.bcms.services.modal.media.picker.hide();
    }
    function done() {
      if (!modalData.value.media) {
        window.bcms.services.notification.warning(
          'You must select a media file.'
        );
        return;
      }
      if (modalData.value.onDone) {
        const result = modalData.value.onDone({
          media: modalData.value.media,
        });
        if (result instanceof Promise) {
          result.catch((error) => {
            console.error(error);
          });
        }
      }
      window.bcms.services.modal.media.picker.hide();
    }

    return () => (
      <Modal
        title={modalData.value.title}
        onCancel={cancel}
        onDone={done}
        show={show.value}
      >
        <div class="bcmsModal--row">
          <BCMSMediaViewer mode="select" />
        </div>
      </Modal>
    );
  },
});
export default component;
</script>

// src/components/modals/media/picker.svelte
<script lang="ts">
  import { createEventDispatcher, onDestroy, onMount } from 'svelte';
  import type { Media, Prop } from '@becomes/cms-sdk';
  import { StoreService, NotificationService } from '../../../services';
  import Modal from '../modal.svelte';
  import { MediaViewer } from '../../media';

  type Data = {
    media: {
      value: Media;
      error: string;
    };
    prop: Prop;
    propIndex: number;
    valueIndex: number;
    depth: string;
  };

  export { className as class };

  const dispatch = createEventDispatcher();
  const modalName = 'MediaPickerModal';
  let className = '';
  let data: Data = getData();
  let unsubscribe: () => void;

  function getData(): Data {
    return {
      media: {
        value: undefined,
        error: '',
      },
      prop: undefined,
      propIndex: -1,
      valueIndex: -1,
      depth: '',
    };
  }

  function close() {
    StoreService.update(modalName, false);
  }
  function cancel() {
    dispatch('cancel');
    close();
  }
  function done() {
    if (!data.media.value) {
      NotificationService.error('Please select a media.');
      return;
    }
    dispatch('done', {
      media: data.media.value,
      prop: data.prop,
      propIndex: data.propIndex,
      valueIndex: data.valueIndex,
      depth: data.depth,
    });
    close();
  }

  onMount(() => {
    unsubscribe = StoreService.subscribe(modalName, async (value) => {
      data.prop = value.prop;
      data.propIndex = value.propIndex;
      data.valueIndex = value.valueIndex;
      data.depth = value.depth;
    });
  });
  onDestroy(async () => {
    unsubscribe();
  });
</script>

<Modal
  title="Media picker"
  name={modalName}
  class={className}
  on:cancel={cancel}
  on:done={done}
  on:animationDone={() => {
    data = getData();
  }}>
  <div class="bcmsModal--row">
    <MediaViewer
      isItemSelect={true}
      on:selected={(event) => {
        data.media.value = event.detail;
      }}
      on:redirect
      on:file />
  </div>
</Modal>
