// src/components/props/enum.vue
<script lang="tsx">
import { computed, defineComponent, onUnmounted, PropType, ref } from 'vue';
import type { BCMSProp, BCMSPropEnum } from '@becomes/cms-sdk/types';
import { DefaultComponentProps } from '../_default';
import { BCMSPropWrapper } from './_wrapper';
import { BCMSSelect } from '../input';

type PropValueType = BCMSPropEnum;

const component = defineComponent({
  props: {
    ...DefaultComponentProps,
    prop: {
      type: Object as PropType<BCMSProp>,
      required: true,
    },
    onUpdate: Function as PropType<(prop: BCMSProp) => void | Promise<void>>,
  },
  emits: {
    update: (_prop: BCMSProp) => {
      return true;
    },
  },
  setup(props, ctx) {
    const propsValue = computed(() => {
      return props.prop.value as PropValueType;
    });
    const error = ref('');
    const unregisterFromChecker = window.bcms.services.propsChecker.register(
      () => {
        let isOk = true;
        if (props.prop.required) {
          const value = props.prop.value as PropValueType;
          if (!value.selected) {
            error.value = 'Please select an option';
          } else {
            error.value = '';
          }
        }
        return isOk;
      }
    );

    onUnmounted(() => {
      unregisterFromChecker();
    });

    return () => (
      <BCMSPropWrapper
        id={props.id}
        cyTag="prop-enum"
        class={props.class}
        style={props.style}
        prop={props.prop}
      >
        <div class="prop--enum">
          <BCMSSelect
            selected={propsValue.value.selected}
            placeholder={props.prop.label}
            invalidText={error.value}
            options={propsValue.value.items.map((item) => {
              return {
                value: item,
                label: item,
              };
            })}
            onChange={(data) => {
              const prop = window.bcms.services.general.objectInstance(
                props.prop
              );
              (prop.value as PropValueType).selected = data.value;
              ctx.emit('update', prop);
            }}
          />
        </div>
      </BCMSPropWrapper>
    );
  },
});
export default component;
</script>

// src/components/props/enum.svelte
<script lang="ts">
  import { beforeUpdate, createEventDispatcher, onDestroy } from 'svelte';
  import type { Prop, PropEnum } from '@becomes/cms-sdk';
  import { Select } from '../input';
  import SinglePropWrapper from './single-prop-wrapper.svelte';
  import { PropsCheckerService } from '../../services';

  export { className as class };
  export let prop: Prop;

  const unregisterFromChecher = PropsCheckerService.register(() => {
    let isOk = true;
    if (prop.required) {
      if (!value.selected) {
        error = 'Option must be selected.';
        isOk = false;
      } else {
        error = '';
      }
    }
    return isOk;
  });
  const dispatch = createEventDispatcher();
  let className = '';
  let value = prop.value as PropEnum;
  let error: string = '';

  function selectItem(name: string) {
    (prop.value as PropEnum).selected = name;
    dispatch('update', prop);
  }
  beforeUpdate(() => {
    value = prop.value as PropEnum;
  });
  onDestroy(() => {
    unregisterFromChecher();
  });
</script>

<SinglePropWrapper cyTag="prop-enum" class={className} {prop}>
  <div class="prop--enum">
    <Select
      placeholder="Select one"
      selected={value.selected}
      invalidText={error}
      options={value.items.map((e) => {
        return { label: e, value: e };
      })}
      on:change={(event) => {
        value.selected = event.detail.value;
        selectItem(event.detail.value);
      }} />
  </div>
</SinglePropWrapper>
