// src/components/input/select/entry-pointer.svelte
<script lang="ts">
  import {
    onMount,
    createEventDispatcher,
    onDestroy,
    beforeUpdate,
  } from 'svelte';
  import type { Template } from '@becomes/cms-sdk';
  import { GeneralService, sdk, StoreService } from '../../../services';
  import Select from './select.svelte';

  export { className as class };
  export let exclude: string[] = [];
  export let selected: string = undefined;
  export let invalidText = '';

  const templateStoreUnsub = StoreService.subscribe(
    'template',
    async (value: Template[]) => {
      if (value) {
        templates = value;
        if (exclude.length > 0) {
          templates = templates.filter((e) => !exclude.includes(e._id));
        }
      }
    }
  );
  const dispatch = createEventDispatcher();
  let className = '';
  let templates: Template[] = [];
  let selectedTemplate: Template;

  onMount(async () => {
    templates = await GeneralService.errorWrapper(
      async () => {
        return await sdk.template.getAll();
      },
      async (value: Template[]) => {
        return value;
      }
    );
    if (exclude.length > 0) {
      templates = templates.filter((e) => !exclude.includes(e._id));
    }
  });
  onDestroy(() => {
    templateStoreUnsub();
  });
  beforeUpdate(() => {
    selectedTemplate = templates.find((e) => e._id === selected);
  });
</script>

<Select
  cyTag={'entryPointer'}
  class={className}
  label="Select a template"
  placeholder="Select a template"
  {invalidText}
  options={templates.map((e) => {
    return { label: e.label, value: e._id };
  })}
  disabled={templates.length === 0}
  selected={selectedTemplate ? selectedTemplate._id : ''}
  on:change={(event) => {
    if (event.detail.value === '') {
      dispatch('select', undefined);
      return;
    }
    dispatch('select', event.detail.value);
  }} />

// src/components/input/select/entry-pointer.tsx
import { computed, defineComponent, onMounted, PropType } from 'vue';
import { DefaultComponentProps } from '../../_default';
import type { BCMSSelectOption } from '../../../types';
import { BCMSStoreMutationTypes } from '../../../types';
import BCMSSelect from './main';
import { useTranslation } from '../../../translations';

const component = defineComponent({
  props: {
    ...DefaultComponentProps,
    exclude: {
      type: Array as PropType<string[]>,
      default: () => [],
    },
    selected: String,
    invalidText: String,
  },
  emits: {
    change: (_value: BCMSSelectOption) => {
      return true;
    },
  },
  setup(props, ctx) {
    const throwable = window.bcms.util.throwable;
    const store = window.bcms.vue.store;
    const translations = computed(() => {
      return useTranslation();
    });
    const templates = computed(() => {
      return store.getters.template_items;
    });

    onMounted(async () => {
      if (templates.value.length === 0) {
        await throwable(
          async () => {
            return await window.bcms.sdk.template.getAll();
          },
          async (result) => {
            store.commit(BCMSStoreMutationTypes.template_set, result);
          }
        );
      }
    });

    return () => (
      <BCMSSelect
        cyTag={props.cyTag ? props.cyTag : 'entryPointer'}
        class={props.class}
        label={translations.value.input.entryPointer.label}
        placeholder={translations.value.input.entryPointer.placeholder}
        invalidText={props.invalidText}
        options={templates.value.map((e) => {
          return { label: e.label, value: e._id };
        })}
        selected={props.selected ? props.selected : ''}
        disabled={templates.value.length === 0}
        onChange={(value) => {
          ctx.emit('change', value);
        }}
      />
    );
  },
});
export default component;
