// src/components/input/select/group-pointer.tsx
import { computed, defineComponent, onMounted, PropType } from 'vue';
import { DefaultComponentProps } from '../../_default';
import type { BCMSSelectOption } from '../../../types';
import { BCMSStoreMutationTypes } from '../../../types';
import BCMSSelect from './main';
import type { BCMSGroup } from '@becomes/cms-sdk/types';
import { useTranslation } from '../../../translations';

const component = defineComponent({
  props: {
    ...DefaultComponentProps,
    exclude: {
      type: Array as PropType<string[]>,
      default: () => [],
    },
    selected: String,
    invalidText: String,
  },
  emits: {
    change: (_value: BCMSSelectOption) => {
      return true;
    },
  },
  setup(props, ctx) {
    const throwable = window.bcms.util.throwable;
    const store = window.bcms.vue.store;
    const translations = computed(() => {
      return useTranslation();
    });
    const groups = computed(() => {
      return (
        JSON.parse(JSON.stringify(store.getters.group_items)) as BCMSGroup[]
      ).sort((a, b) => (b.label < a.label ? 1 : -1));
    });

    onMounted(async () => {
      if (groups.value.length === 0) {
        await throwable(
          async () => {
            return await window.bcms.sdk.group.getAll();
          },
          async (result) => {
            store.commit(BCMSStoreMutationTypes.group_set, result);
          }
        );
      }
    });

    return () => (
      <BCMSSelect
        cyTag={props.cyTag ? props.cyTag : 'groupPointer'}
        class={props.class}
        label={translations.value.input.groupPointer.label}
        placeholder={translations.value.input.groupPointer.placeholder}
        invalidText={props.invalidText}
        options={groups.value.map((e) => {
          return { label: e.label, value: e._id };
        })}
        selected={props.selected ? props.selected : ''}
        disabled={groups.value.length === 0}
        onChange={(value) => {
          ctx.emit('change', value);
        }}
      />
    );
  },
});
export default component;

// src/components/input/select/group-pointer.svelte
<script lang="ts">
  import {
    onMount,
    onDestroy,
    createEventDispatcher,
    beforeUpdate,
  } from 'svelte';
  import type { Group } from '@becomes/cms-sdk';
  import { StoreService, GeneralService, sdk } from '../../../services';
  import Select from './select.svelte';
  import type { SelectOption } from '../../../types';

  export { className as class };
  export let exclude: string = undefined;
  export let selected: string = undefined;
  export let invalidText = '';

  const groupStoreUnsub = StoreService.subscribe(
    'group',
    async (value: Group[]) => {
      if (value) {
        groups = value;
        if (exclude !== '') {
          groups = groups.filter((e) => e._id !== exclude);
        }
      }
    }
  );
  const dispatch = createEventDispatcher();
  let className = '';
  let groups: Group[] = [];

  onMount(async () => {
    groups = await GeneralService.errorWrapper(
      async () => {
        return await sdk.group.getAll();
      },
      async (value: Group[]) => {
        return value;
      }
    );
    if (exclude) {
      groups = groups.filter((e) => e._id !== exclude);
    }
  });
  onDestroy(() => {
    groupStoreUnsub();
  });
</script>

<Select
  class={className}
  label="Select a group"
  placeholder="Select a group"
  {invalidText}
  options={groups.map((e) => {
    return { label: e.label, value: e._id };
  })}
  selected={selected ? selected : ''}
  disabled={groups.length === 0}
  on:change={(event) => {
    dispatch('select', event.detail.value);
  }} />
