// src/components/input/select/index.vue
<script lang="tsx">
import { computed, defineComponent, PropType, ref } from 'vue';
import * as uuid from 'uuid';
import { BCMSSelectOption } from '../../../types';
import BCMSIcon from '../../icon.vue';
import InputWrapper from '../_input.vue';
import { DefaultComponentProps } from '../../_default';

const component = defineComponent({
  props: {
    ...DefaultComponentProps,
    label: String,
    placeholder: String,
    invalidText: String,
    helperText: String,
    disabled: {
      type: Boolean,
      default: false,
    },
    selected: {
      type: String,
      default: '',
    },
    options: {
      type: Array as PropType<BCMSSelectOption[]>,
      default: () => [],
    },
    hasSearch: {
      type: Boolean,
      default: false,
    },
  },
  emits: {
    change: (_option: BCMSSelectOption) => {
      return true;
    },
  },
  setup(props, ctx) {
    const scrollerId = uuid.v4();
    const bcmsDropdownList = ref<HTMLUListElement | null>(null);
    const search = ref('');
    const toggler = ref<HTMLButtonElement | null>(null);
    const filteredOptions = computed<BCMSSelectOption[]>(() => {
      return props.options.filter((option) =>
        search.value
          ? option.value.toLowerCase().includes(search.value) ||
            option.label.toLowerCase().includes(search.value)
          : true
      );
    });
    const isDropdownActive = ref(false);
    const logic = {
      handleSearchInput(event: Event) {
        const element = event.target as HTMLInputElement;
        if (!element) {
          return;
        }
        search.value = element.value.toLowerCase();
        // const searchString = element.value.toLowerCase();
        // filteredOptions.value = props.options.filter(
        //   (option) =>
        //     option.value.toLowerCase().includes(searchString) ||
        //     option.label.toLowerCase().includes(searchString)
        // );
      },
      toggleDropdown() {
        isDropdownActive.value = !isDropdownActive.value;
        if (isDropdownActive.value) {
          window.addEventListener('keydown', eventListeners);
        } else {
          window.removeEventListener('keydown', eventListeners);
        }
      },
      getPlaceholderText(_selected: string) {
        if (!_selected) {
          return props.placeholder;
        }
        const selectedOption = props.options.find((e) => e.value === _selected);
        if (!selectedOption) {
          return props.placeholder;
        }
        return selectedOption.label
          ? selectedOption.label
          : selectedOption.value;
      },
      isItemSelected(item: BCMSSelectOption) {
        return item.value === props.selected;
      },
      selectOption(option: BCMSSelectOption) {
        if (option.value === props.selected) {
          ctx.emit('change', { label: '', value: '' });
        } else {
          ctx.emit('change', option);
        }
        isDropdownActive.value = true;
      },
    };
    function eventListeners(event: KeyboardEvent) {
      const dropDown = {
        root: bcmsDropdownList.value,
        active:
          (bcmsDropdownList.value?.querySelector(
            'li:focus'
          ) as HTMLLIElement) ||
          (bcmsDropdownList.value?.querySelector(
            '._bcmsInput--select-list-item_selected'
          ) as HTMLLIElement),
        firstItem: bcmsDropdownList.value?.querySelector(
          'li:first-child'
        ) as HTMLLIElement,
        lastItem: bcmsDropdownList.value?.querySelector(
          'li:last-child'
        ) as HTMLLIElement,
      };

      switch (event.key) {
        case 'Escape': // 'ESC' - Close dropdown
          event.preventDefault();
          logic.toggleDropdown();
          break;

        case 'ArrowUp': // 'ARROW UP' - Move up
          event.preventDefault();
          if (!dropDown.active || !dropDown.active?.previousSibling) {
            dropDown.lastItem.focus();
          } else {
            const prevSibl = dropDown.active.previousSibling as HTMLLIElement;
            prevSibl.focus();
          }
          break;

        case 'ArrowDown': // 'ARROW DOWN - Move down
          event.preventDefault();
          if (!dropDown.active || !dropDown.active?.nextSibling) {
            dropDown.firstItem.focus();
          } else {
            const nextSibling = dropDown.active.nextSibling as HTMLLIElement;
            nextSibling.focus();
          }
          break;

        default:
          break;
      }
    }

    return () => {
      return (
        <InputWrapper
          class={`${props.class} _bcmsInput_selectWidth`}
          label={props.label}
          invalidText={props.invalidText}
          helperText={props.helperText}
        >
          {props.hasSearch ? (
            <div
              id={props.id}
              v-cy={props.cyTag}
              class="_bcmsInput--select-search"
            >
              <BCMSIcon src="/search" />
              <input
                class="_bcmsInput--select-search-input"
                type="text"
                placeholder="Search"
                onKeyup={logic.handleSearchInput}
              />
            </div>
          ) : (
            <button
              id={'' + props.id}
              v-cy={props.cyTag}
              aria-haspopup="listbox"
              aria-labelledby="bcmsSelect_label bcmsSelect_button"
              type="button"
              class={`_bcmsInput--select-toggler ${
                (isDropdownActive.value || props.hasSearch) && !props.disabled
                  ? '_bcmsInput--select-toggler_active'
                  : ''
              }`}
              onClick={() => {
                logic.toggleDropdown();
              }}
              disabled={props.disabled}
              ref={toggler}
            >
              <span
                class={!props.selected ? '_bcmsInput--select-placeholder' : ''}
              >
                {logic.getPlaceholderText(props.selected)}
              </span>
              <BCMSIcon src="/chevron/down" />
            </button>
          )}
          {(isDropdownActive.value || props.hasSearch) && !props.disabled ? (
            <ul
              id={scrollerId}
              tabindex="-1"
              role="listbox"
              aria-labelledby="bcmsSelect_label"
              class={`_bcmsInput--select-list ${
                props.hasSearch ? '_bcmsInput--select-search-list' : ''
              } bcmsScrollbar`}
              ref={bcmsDropdownList}
              v-clickOutside={() => (isDropdownActive.value = false)}
            >
              {filteredOptions.value.map((option) => (
                <li
                  role="option"
                  tabindex="0"
                  class={`_bcmsInput--select-list-item ${
                    logic.isItemSelected(option)
                      ? '_bcmsInput--select-list-item_selected'
                      : ''
                  } ${
                    option.special
                      ? `_bcmsInput--select-list-item_${option.special}`
                      : ''
                  }`}
                  data-value={option.value}
                  onKeydown={(event) => {
                    if (event.key === 'Enter') {
                      logic.selectOption(option);
                    }
                  }}
                  onClick={() => {
                    logic.selectOption(option);
                  }}
                >
                  {option.label ? option.label : option.value}
                </li>
              ))}
            </ul>
          ) : (
            ''
          )}
        </InputWrapper>
      );
    };
  },
});
export default component;
</script>

// src/components/input/select/select.svelte
<script lang="ts">
  import InputWrapper from '../_input.svelte';
  import type { SelectOption } from '../../../types';
  import { beforeUpdate, createEventDispatcher } from 'svelte';
  import * as uuid from 'uuid';
  import { ClickOutsideService, cy } from '../../../services';
  import { ChevronDownIcon, SearchIcon } from '../../icons';

  export { className as class };
  export let label = '';
  export let placeholder = '';
  export let invalidText = '';
  export let helperText: string = undefined;
  export let disabled = false;
  export let selected: string = '';
  export let options: SelectOption[] = [];
  export let hasSearch: boolean = false;
  export let cyTag: string = undefined;

  const scrollerId = uuid.v4();
  const dispatch = createEventDispatcher();
  let className = '';
  let isDropdownActive = false;
  let bcmsDropdownList: HTMLUListElement;
  let stateLatch = false;
  let filteredOptions: SelectOption[] = options.map((e) => {
    return {
      _id: uuid.v4(),
      ...e,
    };
  });

  const closeDropdown = ClickOutsideService.bind(() => {
    toggleDropdown();
    stateLatch = true;
  });

  function toggleDropdown() {
    if (stateLatch) {
      stateLatch = false;
      return;
    }
    isDropdownActive = !isDropdownActive;
    if (isDropdownActive) {
      window.addEventListener('keydown', eventListeners);
    } else {
      window.removeEventListener('keydown', eventListeners);
    }
  }
  function eventListeners(event: KeyboardEvent) {
    const dropDown = {
      root: bcmsDropdownList as HTMLUListElement,
      active:
        (bcmsDropdownList?.querySelector('li:focus') as HTMLLIElement) ||
        (bcmsDropdownList?.querySelector(
          '._bcmsInput--select-list-item_selected'
        ) as HTMLLIElement),
      firstItem: bcmsDropdownList?.querySelector(
        'li:first-child'
      ) as HTMLLIElement,
      lastItem: bcmsDropdownList?.querySelector(
        'li:last-child'
      ) as HTMLLIElement,
    };

    switch (event.key) {
      case 'Escape': // 'ESC' - Close dropdown
        event.preventDefault();
        toggleDropdown();
        break;

      case 'ArrowUp': // 'ARROW UP' - Move up
        event.preventDefault();
        if (!dropDown.active || !dropDown.active?.previousSibling) {
          dropDown.lastItem.focus();
        } else {
          const prevSibl = dropDown.active.previousSibling as HTMLLIElement;
          prevSibl.focus();
        }
        break;

      case 'ArrowDown': // 'ARROW DOWN - Move down
        event.preventDefault();
        if (!dropDown.active || !dropDown.active?.nextSibling) {
          dropDown.firstItem.focus();
        } else {
          const nextSibling = dropDown.active.nextSibling as HTMLLIElement;
          nextSibling.focus();
        }
        break;

      default:
        break;
    }
  }
  function isItemSelected(item: SelectOption) {
    return item.value === selected;
  }
  function selectOption(option: SelectOption) {
    if (option.value === selected) {
      dispatch('change', { label: '', value: '' });
    } else {
      dispatch('change', {
        label: option.label,
        value: option.value,
        _id: option._id || '',
      });
    }
    toggleDropdown();
  }
  function getPlaceholderText(_selected: string) {
    if (!_selected) {
      return placeholder;
    }
    const selectedOption = options.find((e) => e.value === _selected);
    if (!selectOption) {
      return placeholder;
    }
    return selectedOption.label ? selectedOption.label : selectedOption.value;
  }
  function handleSearchInput(event: Event) {
    const element = event.target as HTMLInputElement;
    if (!element) {
      return;
    }
    const searchString = element.value.toLowerCase();
    filteredOptions = options.filter(
      (option) =>
        option.value.toLowerCase().includes(searchString) ||
        option.label.toLowerCase().includes(searchString)
    );
  }
  beforeUpdate(() => {
    if (
      !hasSearch &&
      (filteredOptions.length > options.length ||
        JSON.stringify(filteredOptions) !== JSON.stringify(options))
    ) {
      filteredOptions = options.map((e) => {
        return {
          _id: uuid.v4(),
          ...e,
        };
      });
    }
  });
</script>

<InputWrapper
  class="{className} _bcmsInput_selectWidth"
  {label}
  {invalidText}
  {helperText}>
  <div use:cy={cyTag} class="_bcmsInput--select">
    {#if hasSearch}
      <div class="_bcmsInput--select-search">
        <SearchIcon />
        <input
          class="_bcmsInput--select-search-input"
          type="text"
          placeholder="Search"
          on:keyup={handleSearchInput} />
      </div>
    {:else}
      <button
        aria-haspopup="listbox"
        aria-labelledby="bcmsSelect_label bcmsSelect_button"
        id="bcmsSelect_button"
        type="button"
        class="_bcmsInput--select-toggler {(isDropdownActive || hasSearch) && !disabled ? '_bcmsInput--select-toggler_active' : ''}"
        on:click={() => {
          toggleDropdown();
        }}
        {disabled}>
        <span
          class={!selected ? '_bcmsInput--select-placeholder' : ''}>{getPlaceholderText(selected)}</span>
        <ChevronDownIcon />
      </button>
    {/if}
    {#if (isDropdownActive || hasSearch) && !disabled}
      <ul
        id={scrollerId}
        use:closeDropdown
        tabindex="-1"
        role="listbox"
        aria-labelledby="bcmsSelect_label"
        class="_bcmsInput--select-list {hasSearch ? '_bcmsInput--select-search-list' : ''} customScrollbar"
        bind:this={bcmsDropdownList}>
        {#each filteredOptions as option}
          <li
            id={option._id}
            role="option"
            tabindex="-1"
            class="_bcmsInput--select-list-item {isItemSelected(option) ? '_bcmsInput--select-list-item_selected' : ''}"
            data-value={option.value}
            on:keydown={(event) => {
              if (event.key === 'Enter') {
                selectOption(option);
              }
            }}
            on:click={() => {
              selectOption(option);
            }}>
            {#if option.imgUrl}
              <img src={option.imgUrl} alt={option.label} />
            {/if}
            {option.label ? option.label : option.value}
          </li>
        {/each}
      </ul>
    {/if}
  </div>
</InputWrapper>
