// src/components/input/multi-add/multi-add.svelte
<script lang="ts">
  import InputWrapper from '../_input.svelte';
  import { createEventDispatcher } from 'svelte';
  import { fade } from 'svelte/transition';
  import { MultiAddInputItem } from './';

  export { className as class };
  export let value: string[] = [];
  export let placeholder = '';
  export let label = '';
  export let invalidText = '';
  export let helperText: string = undefined;
  export let disabled = false;
  export let formater: (value: string) => string = undefined;
  export let validate: (items: string[]) => string = undefined;

  const dispatch = createEventDispatcher();
  let className = '';
  let items: string[] = [...value];

  function handleInput(event: Event | KeyboardEvent) {
    const element = event.target as HTMLInputElement;
    if (!element) {
      return;
    }
    if ((event as KeyboardEvent).key === 'Enter' && element.value) {
      if (typeof validate === 'function') {
        const error = validate([...items, element.value]);
        if (error) {
          invalidText = error;
          return;
        }
      }
      items = [...items, element.value];
      element.value = '';
      dispatch('update', items);
    } else {
      if (typeof formater === 'function') {
        element.value = formater(element.value);
      }
    }
  }
</script>

<InputWrapper class={className} {label} {invalidText} {helperText}>
  <input
    id={label}
    class="_bcmsInput--text"
    {placeholder}
    {disabled}
    on:change={handleInput}
    on:keyup={handleInput} />
  <div class="_bcmsInput--multiAdd" in:fade={{ duration: 300, delay: 300 }}>
    <ul>
      {#each items as item}
        <MultiAddInputItem
          {item}
          {disabled}
          on:remove={() => {
            items = items.filter((e) => e !== item);
            dispatch('update', items);
          }} />
      {/each}
    </ul>
  </div>
</InputWrapper>

// src/components/input/multi-add/index.vue
<script lang="tsx">
import { defineComponent, onBeforeUpdate, onMounted, PropType, ref } from 'vue';
import InputWrapper from '../_input.vue';
import BCMSMultiAddItem from './item.vue';
import { DefaultComponentProps } from '../../_default';

const component = defineComponent({
  props: {
    ...DefaultComponentProps,
    value: {
      type: Array as PropType<string[]>,
      required: true,
    },
    placeholder: String,
    label: String,
    invalidText: String,
    helperText: String,
    disabled: {
      type: Boolean,
      default: false,
    },
    format: Function as PropType<(value: string) => string>,
    validate: Function as PropType<(value: string[]) => string | null>,
    focusOnLoad: Boolean,
  },
  emits: {
    input: (_value: string[]) => {
      return true;
    },
  },
  setup(props, ctx) {
    const inputRef = ref<HTMLInputElement | null>(null);
    const itemsBuffer = ref(props.value);
    const items = ref(props.value);
    const invalidText = ref(props.invalidText);

    onBeforeUpdate(async () => {
      let update = false;
      if (itemsBuffer.value.length !== props.value.length) {
        update = true;
      } else {
        for (let i = 0; i < props.value.length; i++) {
          if (itemsBuffer.value[i] !== props.value[i]) {
            update = true;
            break;
          }
        }
      }
      if (update) {
        itemsBuffer.value = props.value;
        items.value = props.value;
      }
    });

    onMounted(() => {
      setTimeout(() => {
        if (props.focusOnLoad && inputRef.value) {
          inputRef.value.focus();
        }
      }, 0);
    });

    function handleInput(event: Event | KeyboardEvent) {
      const element = event.target as HTMLInputElement;
      if (!element) {
        return;
      }
      if ((event as KeyboardEvent).key === 'Enter' && element.value) {
        if (typeof props.validate === 'function') {
          const error = props.validate([...items.value, element.value]);
          if (error) {
            invalidText.value = error;
            return;
          }
        }
        items.value = [...items.value, element.value];
        element.value = '';
        ctx.emit('input', items.value);
      } else {
        if (typeof props.format === 'function') {
          element.value = props.format(element.value);
        }
      }
    }

    return () => (
      <InputWrapper
        class={props.class}
        label={props.label}
        invalidText={props.invalidText ? props.invalidText : invalidText.value}
        helperText={props.helperText}
      >
        <input
          ref={inputRef}
          class={`relative block w-full bg-white border rounded-3.5 transition-all duration-300 shadow-none font-normal not-italic text-base leading-tight -tracking-0.01 text-dark h-11 py-0 px-4.5 outline-none placeholder-grey placeholder-opacity-100 pt-3 pb-[9px] pl-4.5 resize-none top-0 left-0 overflow-hidden hover:shadow-input focus-within:shadow-input ${
            props.invalidText
              ? 'border-red hover:border-red focus-within:border-red pr-11'
              : 'pr-6'
          } ${
            props.invalidText
              ? ''
              : 'border-grey hover:border-grey hover:border-opacity-50 focus-within:border-grey focus-within:border-opacity-50'
          } ${
            props.disabled
              ? 'cursor-not-allowed opacity-40 shadow-none border-grey'
              : 'cursor-auto'
          }`}
          id={props.label}
          placeholder={props.placeholder}
          disabled={props.disabled}
          onChange={handleInput}
          onKeyup={handleInput}
        />
        <div class="pt-2.5">
          <ul class="list-none flex flex-wrap gap-[5px]">
            {items.value.map((item) => (
              <BCMSMultiAddItem
                item={item}
                disabled={props.disabled}
                onRemove={() => {
                  items.value = items.value.filter((e) => e !== item);
                  ctx.emit('input', items.value);
                }}
              />
            ))}
          </ul>
        </div>
      </InputWrapper>
    );
  },
});
export default component;
</script>
