// src/components/input/mutli-add/item.vue
<script lang="tsx">
import { defineComponent } from 'vue';
import { BCMSIcon } from '../../index';

const component = defineComponent({
  props: {
    item: {
      type: String,
      required: true,
    },
    disabled: {
      type: Boolean,
      default: false,
    },
  },
  emits: {
    remove: () => {
      return true;
    },
  },
  setup(props, ctx) {
    return () => (
      <li class="_bcmsInput--multiAdd-item">
        <span class="_bcmsInput--multiAdd-label">{props.item}</span>
        <button
          class="_bcmsInput--multiAdd-delete"
          disabled={props.disabled}
          aria-label={`Remove ${props.item}`}
          onClick={() => {
            ctx.emit('remove');
          }}
        >
          <BCMSIcon src="/close" />
        </button>
        <div class="_bcmsInput--multiAdd-bg" />
      </li>
    );
  },
});
export default component;
</script>

// src/components/input/multi-add/item.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import { CloseIcon } from '../../icons';

  export let item: string;
  export let disabled: boolean = false;

  const dispatch = createEventDispatcher();
</script>

<li class="_bcmsInput--multiAdd-item">
  <span class="_bcmsInput--multiAdd-label">{item}</span>
  <button
    class="_bcmsInput--multiAdd-delete"
    {disabled}
    aria-label="Remove {item}"
    on:click={() => {
      dispatch('remove');
    }}
  >
    <CloseIcon />
  </button>
  <div class="_bcmsInput--multiAdd-bg" />
</li>
