// src/components/button.svelte
<script lang="ts">
  export { className as class };
  export let kind: 'primary' | 'secondary' | 'alternate' | 'ghost' | 'danger' =
    'primary';
  export let style: string = undefined;
  export let disabled: boolean = false;
  export let size: 'm' | 's' | '' = '';

  let className = '';
</script>

<button
  class="bcmsButton bcmsButton_{kind}
    {size ? `bcmsButton_${size}` : ''}
    {className}"
  {style}
  {disabled}
  on:click>
  {#if $$slots.default}
    <span>
      <slot />
    </span>
  {/if}
</button>

// src/components/button.vue
<script lang="tsx">
import { defineComponent, PropType } from 'vue';

const component = defineComponent({
  props: {
    kind: {
      type: String as PropType<
        'primary' | 'secondary' | 'alternate' | 'ghost' | 'danger'
      >,
      default: 'primary',
    },
    cyTag: String,
    class: String,
    style: String,
    disabled: Boolean,
    size: String as PropType<'m' | 's'>,
    onClick: Function as PropType<() => void>,
  },
  setup(props, ctx) {
    return () => {
      return (
        <button
          class={`bcmsButton bcmsButton_${props.kind} ${
            props.size ? `bcmsButton_${props.size}` : ''
          } ${props.class ? props.class : ''}`}
          v-cy={props.cyTag}
          style={props.style}
          disabled={props.disabled}
          onClick={() => {
            if (props.onClick) {
              props.onClick();
            }
          }}
        >
          {ctx.slots.default ? <span>{ctx.slots.default()}</span> : ''}
        </button>
      );
    };
  },
});
export default component;
</script>
