// src/components/media/breadcrumb.svelte
<script lang="ts">
  import type { BreadcrumbTreeItem } from '../../types';
  import { beforeUpdate, createEventDispatcher, onMount } from 'svelte';
  import { GeneralService, sdk } from '../../services';
  import type { Media } from '@becomes/cms-sdk';
  import { ChevronRightIcon } from '../icons';

  export let mediaId: string = '';

  const dispatch = createEventDispatcher();
  const buffer = {
    mediaId: '' + mediaId,
  };
  let tree: BreadcrumbTreeItem[] = [];

  async function getParentTree(
    parentId?: string
  ): Promise<
    Array<{
      label: string;
      id: string;
    }>
  > {
    const output: Array<{
      label: string;
      id: string;
    }> = [];
    if (!parentId) {
      return output;
    }
    const parent: Media = await GeneralService.errorWrapper(
      async () => {
        return await sdk.media.get(parentId);
      },
      async (value: Media) => {
        return value;
      }
    );
    if (!parent) {
      return output;
    }
    output.push({
      label: parent.name,
      id: parent._id,
    });
    if (parent.isInRoot) {
      return output;
    }
    return [...output, ...(await getParentTree(parent.parentId))];
  }

  onMount(async () => {
    tree = (await getParentTree(mediaId)).reverse();
  });
  beforeUpdate(async () => {
    if (buffer.mediaId !== mediaId) {
      buffer.mediaId = '' + mediaId;
      tree = (await getParentTree(mediaId)).reverse();
    }
  });
</script>

<nav class="media--breadcrumb">
  <ul class="media--breadcrumb-list">
    <li class="media--breadcrumb-list-item">
      <button
        on:click={() => {
          dispatch('open', '');
        }}><span>Media Manager</span></button>
    </li>
    {#each tree as item}
      <li class="media--breadcrumb-list-item">
        <ChevronRightIcon />
        <button
          on:click={() => {
            dispatch('open', item.id);
          }}><span>{item.label}</span></button>
      </li>
    {/each}
  </ul>
</nav>

// src/components/media/breadcrumb.vue
<script lang="tsx">
import { defineComponent, onBeforeUpdate, onMounted, ref } from 'vue';
import { BCMSMedia, BCMSMediaType } from '@becomes/cms-sdk/types';
import BCMSIcon from '../icon.vue';

const component = defineComponent({
  props: {
    targetMediaId: {
      type: String,
      default: '',
    },
  },
  emits: {
    click: (_media: BCMSMedia) => {
      return true;
    },
  },
  setup(props, ctx) {
    const throwable = window.bcms.util.throwable;
    let lastMediaId = '';
    const tree = ref<BCMSMedia[]>([]);

    async function getParentTree(parentId?: string): Promise<BCMSMedia[]> {
      const output: BCMSMedia[] = [];
      if (!parentId) {
        return output;
      }
      const parent: BCMSMedia | undefined = await throwable(
        async () => {
          return await window.bcms.sdk.media.getById(parentId);
        },
        async (value) => {
          return value;
        }
      );
      if (!parent) {
        return output;
      }
      output.push(parent);
      if (parent.isInRoot) {
        return output;
      }
      return [...output, ...(await getParentTree(parent.parentId))];
    }

    onMounted(async () => {
      lastMediaId = props.targetMediaId;
      tree.value = (await getParentTree(props.targetMediaId)).reverse();
    });
    onBeforeUpdate(async () => {
      if (lastMediaId !== props.targetMediaId) {
        lastMediaId = props.targetMediaId;
        tree.value = (await getParentTree(props.targetMediaId)).reverse();
      }
    });

    return () => (
      <nav class="media--breadcrumb">
        <ul class="media--breadcrumb-list">
          <li class="media--breadcrumb-list-item">
            <button
              onClick={() => {
                ctx.emit('click', {
                  _id: '',
                  type: BCMSMediaType.DIR,
                  createdAt: 0,
                  updatedAt: 0,
                  hasChildren: false,
                  isInRoot: false,
                  mimetype: '',
                  name: '',
                  parentId: '',
                  size: 0,
                  userId: '',
                });
              }}
            >
              <span>Media Manager</span>
            </button>
          </li>
          {tree.value.map((item) => {
            return (
              <li class="media--breadcrumb-list-item">
                <BCMSIcon src="/chevron/right" />
                <button
                  onClick={() => {
                    ctx.emit('click', item);
                  }}
                >
                  <span>{item.name}</span>
                </button>
              </li>
            );
          })}
        </ul>
      </nav>
    );
  },
});
export default component;
</script>
