// src/components/entry/filter.vue
<script lang="tsx">
import { defineComponent, PropType, ref, Transition } from 'vue';
import type { BCMSTemplate } from '@becomes/cms-sdk/types';
import BCMSIcon from '../icon.vue';
import { BCMSEntryFilters } from '../../types';
import BCMSButton from '../button.vue';
import { BCMSDateInput } from '../input';

function getFilters(): BCMSEntryFilters {
  return {
    search: {
      name: '',
    },
    isOpen: false,
    options: [
      {
        label: 'Date Created',
        fromDate: {
          year: -1,
          month: -1,
          day: -1,
        },
      },
      {
        label: 'Date Updated',
        toDate: {
          year: -1,
          month: -1,
          day: -1,
        },
      },
    ],
  };
}

const component = defineComponent({
  props: {
    template: {
      type: Object as PropType<BCMSTemplate>,
      required: true,
    },
    entryCount: {
      type: Number,
      default: 0,
    },
  },
  emits: {
    addEntry: () => {
      return true;
    },
    filter: (_filter: BCMSEntryFilters) => {
      return true;
    },
  },
  setup(props, ctx) {
    const filters = ref(getFilters());
    // eslint-disable-next-line no-undef
    let searchDebounceTimer: NodeJS.Timeout;

    const toggler = ref<HTMLButtonElement | null>(null);

    return () => (
      <header>
        <div class="view--left">
          <h2 class="view--title mb-25">{props.template.label}</h2>
          <p class="view--description">{props.entryCount} entries found</p>
          <div class="view--search">
            <BCMSIcon src="/search" class="view--search-icon" />
            <input
              v-cy={'search'}
              class="view--search-input"
              type="text"
              placeholder="Search entries by Title or ID"
              v-model={filters.value.search.name}
              onKeyup={async () => {
                clearTimeout(searchDebounceTimer);
                searchDebounceTimer = setTimeout(() => {
                  ctx.emit('filter', filters.value);
                }, 300);
              }}
            />
            <Transition name="fade">
              {filters.value.isOpen ? (
                <div
                  class="media--filters"
                  v-clickOutside={() => (filters.value.isOpen = false)}
                >
                  {filters.value.options.map((filterOption) => {
                    return (
                      <div class="media--filter">
                        {filterOption.fromDate ? (
                          <BCMSDateInput
                            label={filterOption.label}
                            value={
                              filterOption.fromDate.year !== -1
                                ? new Date(
                                    `${filterOption.fromDate.year}-${filterOption.fromDate.month}-${filterOption.fromDate.day}`
                                  ).getTime()
                                : 0
                            }
                            onInput={async (value) => {
                              if (filterOption.fromDate) {
                                if (value === 0) {
                                  filterOption.fromDate = {
                                    year: -1,
                                    month: -1,
                                    day: -1,
                                  };
                                } else {
                                  const date = new Date(value);
                                  filterOption.fromDate.year =
                                    date.getFullYear();
                                  filterOption.fromDate.month =
                                    date.getMonth() + 1;
                                  filterOption.fromDate.day = date.getDate();
                                }
                                ctx.emit('filter', filters.value);
                              }
                            }}
                          />
                        ) : filterOption.toDate ? (
                          <BCMSDateInput
                            label={filterOption.label}
                            value={
                              filterOption.toDate.year !== -1
                                ? new Date(
                                    `${filterOption.toDate.year}-${filterOption.toDate.month}-${filterOption.toDate.day}`
                                  ).getTime()
                                : 0
                            }
                            onInput={async (value) => {
                              if (filterOption.toDate) {
                                if (value === 0) {
                                  filterOption.toDate = {
                                    year: -1,
                                    month: -1,
                                    day: -1,
                                  };
                                } else {
                                  const date = new Date(value);
                                  filterOption.toDate.year = date.getFullYear();
                                  filterOption.toDate.month =
                                    date.getMonth() + 1;
                                  filterOption.toDate.day = date.getDate();
                                }
                                ctx.emit('filter', filters.value);
                              }
                            }}
                          />
                        ) : (
                          ''
                        )}
                      </div>
                    );
                  })}
                </div>
              ) : (
                ''
              )}
            </Transition>
            <button
              v-cy={'open-filters'}
              onClick={() => {
                filters.value.isOpen = !filters.value.isOpen;
              }}
              class={`view--search-toggler ${
                filters.value.isOpen ? 'view--search-toggler_active' : ''
              }`}
              ref={toggler}
            >
              <BCMSIcon src="/chevron/down" />
            </button>
          </div>
        </div>
        <div class="view--right">
          <BCMSButton
            cyTag="add-new"
            onClick={() => {
              ctx.emit('addEntry');
            }}
          >
            Add new&nbsp;
            {props.template.label.toLowerCase()}
          </BCMSButton>
        </div>
      </header>
    );
  },
});
export default component;
</script>

// src/components/media/filter.svelte
<script context="module" lang="ts">
  export const MediaFilterActions = {
    reset(): void {
      // Logic is added in a component instance
    },
  };
</script>

<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import { MediaType } from '@becomes/cms-sdk';
  import { DateInput, Select } from '../input';
  import { StoreService } from '../../services';
  import type { MediaFilter } from '../../types';
  import Button from '../button.svelte';

  const dispatch = createEventDispatcher();
  let filters = getFiltersInitialValue();
  let searchDebaunceTimer: NodeJS.Timeout;

  function getFiltersInitialValue(): MediaFilter {
    return {
      search: {
        name: '',
      },
      isOpen: false,
      options: [
        {
          label: 'Type',
          dropdown: {
            items: [
              { label: 'Image', value: MediaType.IMG },
              { label: 'Video', value: MediaType.VID },
              { label: 'Directory', value: MediaType.DIR },
            ],
            selected: {
              label: 'No filters',
              value: '',
            },
          },
        },
        {
          label: 'Date Modified',
          date: {
            year: -1,
            month: -1,
            day: -1,
          },
        },
      ],
    };
  }

  MediaFilterActions.reset = () => {
    filters = getFiltersInitialValue();
    dispatch('reset', filters);
  };
</script>

<header>
  <div class="media--search view--left">
    <i class="fas fa-search" />
    <input
      class="media--search-input"
      type="text"
      placeholder="Search"
      bind:value={filters.search.name}
      on:keyup={async () => {
        clearTimeout(searchDebaunceTimer);
        searchDebaunceTimer = setTimeout(() => {
          dispatch('filter', filters);
        }, 300);
      }} />
    <button
      on:click={() => {
        filters.isOpen = !filters.isOpen;
      }}
      class="media--search-toggler {filters.isOpen ? 'media--search-toggler_active' : ''}">
      <i class="fas fa-chevron-down" />
    </button>
    {#if filters.isOpen}
      <div class="media--filters">
        {#each filters.options as option}
          <div class="media--filter">
            {#if option.dropdown}
              <Select
                placeholder="No filters"
                label={option.label}
                options={option.dropdown.items}
                selected={option.dropdown.selected.value}
                on:change={async (event) => {
                  option.dropdown.selected = event.detail;
                  dispatch('filter', filters);
                }} />
            {:else if option.date}
              <DateInput
                label={option.label}
                value={option.date.year !== -1 ? `${option.date.year}-${option.date.month}-${option.date.day}` : ''}
                on:input={async (event) => {
                  if (event.detail === 0) {
                    option.date = { year: -1, month: -1, day: -1 };
                  } else {
                    const date = new Date(event.detail);
                    option.date.year = date.getFullYear();
                    option.date.month = date.getMonth() + 1;
                    option.date.day = date.getDate();
                  }
                  dispatch('filter', filters);
                }} />
            {/if}
          </div>
        {/each}
      </div>
    {/if}
  </div>
  <div class="view--right">
    <Button class="mr--20 uploadFileToggler">Upload file</Button>
    <Button
      kind="secondary"
      on:click={() => {
        StoreService.update('MediaAddUpdateFolderModal', true);
      }}>
      Create new folder
    </Button>
  </div>
</header>
