// src/components/media/item.svelte
<script lang="ts">
  import { Media, MediaType } from '@becomes/cms-sdk';
  import { createEventDispatcher } from 'svelte';
  import { FileIcon, FolderIcon, TrashIcon } from '../icons';
  import Image from '../image.svelte';

  export let selected: boolean = false;
  export let item: Media;

  const dispatch = createEventDispatcher();
</script>

<li
  class="media--item media--item_{item.type}
    {selected ? 'media--item_selected' : ''}"
>
  <button
    class="media--item-click"
    title={item.name}
    on:click={() => {
      dispatch('open');
    }}
  >
    {#if item.type !== MediaType.DIR}
      <div class="media--item-visual">
        <div class="media--item-visual-inner">
          {#if item.type === MediaType.IMG || item.type === MediaType.GIF || item.type === MediaType.VID}
            <Image media={item} alt={item.name} />
          {:else}
            <FileIcon />
          {/if}
        </div>
      </div>
    {/if}
    <div class="media--item-footer">
      {#if item.type === MediaType.DIR}
        <FolderIcon class="media--item-icon" />
      {/if}
      <span class="media--item-name">{item.name}</span>
      <button
        class="media--item-delete"
        on:click|stopPropagation|preventDefault={() => {
          dispatch('remove', item);
        }}
      >
        <TrashIcon />
      </button>
    </div>
  </button>
</li>

// src/components/media/item.vue
<script lang="tsx">
import { defineComponent, PropType, reactive } from 'vue';
import { BCMSMedia, BCMSMediaType } from '@becomes/cms-sdk/types';
import { DefaultComponentProps } from '../_default';
import BCMSIcon from '../icon.vue';
import BCMSImage from '../image.vue';

const component = defineComponent({
  props: {
    ...DefaultComponentProps,
    selected: {
      type: Boolean,
      default: false,
    },
    item: {
      type: Object as PropType<BCMSMedia>,
      required: true,
    },
  },
  emits: {
    open: () => {
      return true;
    },
    remove: () => {
      return true;
    },
  },
  setup(props, ctx) {
    props = reactive(props);
    return () => (
      <li
        class={`media--item media--item_${props.item.type} ${
          props.selected ? 'media--item_selected' : ''
        }`}
      >
        <button
          class="media--item-click"
          title={props.item.name}
          onClick={() => {
            ctx.emit('open');
          }}
        >
          {props.item.type !== BCMSMediaType.DIR ? (
            <div class="media--item-visual">
              <div class="media--item-visual-inner">
                {props.item.type === BCMSMediaType.IMG ||
                props.item.type === BCMSMediaType.VID ||
                props.item.type === BCMSMediaType.GIF ? (
                  <>
                    <BCMSImage media={props.item} alt={props.item.name} />
                    <div class="type">{props.item.type}</div>
                  </>
                ) : (
                  <BCMSIcon src="/file" />
                )}
              </div>
            </div>
          ) : (
            ''
          )}
          <div class="media--item-footer">
            {props.item.type === BCMSMediaType.DIR ? (
              <BCMSIcon class="media--item-icon" src="/folder" />
            ) : (
              ''
            )}
            <span class="media--item-name">{props.item.name}</span>
            <button
              class="media--item-delete"
              onClick={(event) => {
                event.stopPropagation();
                event.preventDefault();
                ctx.emit('remove');
              }}
            >
              <BCMSIcon src="/trash" />
            </button>
          </div>
        </button>
      </li>
    );
  },
});
export default component;
</script>
