// src/components/media/viewer.svelte
<script context="module" lang="ts">
  export const chunkSize = 18;
  export const lastState = {
    mediaId: '',
  };
  export const filterMedia = (media: Media[], filter: MediaFilterType) => {
    if (filter.search.name.length > 2) {
      media = media.filter((item) =>
        item.name
          .toLowerCase()
          .includes(filter.search.name.trim().toLowerCase())
      );
    }
    for (const i in filter.options) {
      const option = filter.options[i];
      if (option.dropdown && option.dropdown.selected.value !== '') {
        media = media.filter(
          (item) => item.type === option.dropdown.selected.value
        );
      } else if (option.date && option.date.year !== -1) {
        media = media.filter((item) => {
          const date = new Date(item.updatedAt);
          return (
            date.getFullYear() === option.date.year &&
            date.getMonth() + 1 === option.date.month &&
            date.getDate() === option.date.day
          );
        });
      }
    }
    return media;
  };
</script>

<script lang="ts">
  import {
    beforeUpdate,
    createEventDispatcher,
    onDestroy,
    onMount,
  } from 'svelte';
  import { Media, MediaType } from '@becomes/cms-sdk';
  import type { UppyFile } from '@uppy/core';
  import {
    ConfirmService,
    GeneralService,
    MediaService,
    ModalService,
    NotificationService,
    sdk,
    StoreService,
  } from '../../services';
  import { Breadcrumb } from '../index';
  import { MediaAddUpdateFolderModal, MediaRemoveFileModal } from '../modals';
  import MediaItem from './item.svelte';
  import type { MediaFilter as MediaFilterType } from '../../types';
  import MediaFilter, { MediaFilterActions } from './filter.svelte';
  import { ArrowUpIcon } from '../icons';
  import { Router } from '@becomes/svelte-router';
  import Spinner from '../spinner.svelte';

  export let mediaId: string;
  export let isItemSelect: boolean = false;

  interface MediaInView {
    dirs: Media[];
    files: Media[];
  }

  const mediaStoreUnsub = StoreService.subscribe(
    'media',
    async (value: Media[]) => {
      if (value) {
        mediaInView = await getMedia(value);
      }
    }
  );
  const dispatch = createEventDispatcher();
  const buffer = {
    mediaId: !mediaId ? undefined : '' + mediaId,
  };
  let mediaInView: MediaInView = {
    dirs: [],
    files: [],
  };
  let sortData = {
    name: {
      direction: -1,
    },
  };
  let selectedItem: Media;
  let chunk = 0;
  let showFilesToIndex = chunkSize + chunk * chunkSize;
  let uploading = {
    active: false,
    fileName: '',
    progress: 0,
  };

  function sortMedia(media: MediaInView, toggle?: boolean): MediaInView {
    if (toggle) {
      if (sortData.name.direction === -1) {
        sortData.name.direction = 1;
      } else {
        sortData.name.direction = -1;
      }
    }
    return {
      dirs: media.dirs.sort((a, b) =>
        a.name > b.name ? sortData.name.direction : -sortData.name.direction
      ),
      files: media.files.sort((a, b) =>
        a.name > b.name ? sortData.name.direction : -sortData.name.direction
      ),
    };
  }
  async function createFiles(mediaId: string, name: string, files: File[]) {
    uploading.active = true;
    const errors = await MediaService.createFiles(
      mediaId,
      name,
      files,
      (fileName, event: any) => {
          uploading.fileName = fileName;
          uploading.progress = event.loaded * 100 / event.total;
      }
    );
    if (errors.length > 0) {
      console.error(errors);
      NotificationService.error(
        'Upload completed with errors.' +
          ' See console for more information.' +
          ' This files were not uploaded: ' +
          errors.map((e) => e.filename).join(', ')
      );
    } else {
      NotificationService.success('Files uploaded successfully.');
    }
    StoreService.update('media', await sdk.media.getAll());
    dispatch('file');
    uploading.active = false;
    uploading.fileName = '';
    uploading.progress = 0;
  }
  async function handleMediaClick(item: Media) {
    if (isItemSelect) {
      if (item.type === MediaType.DIR) {
        mediaId = item._id;
        lastState.mediaId = mediaId;
        mediaInView = await getMedia();
      } else {
        selectedItem = item;
        dispatch('selected', item);
      }
    } else {
      if (item.type === MediaType.DIR) {
        if (item._id) {
          Router.navigate(`/dashboard/media/editor/${item._id}`, {
            replace: true,
          });
        } else {
          Router.navigate('/dashboard/media/editor/-', {
            replace: true,
          });
        }
      } else {
        const buffer: Buffer = await GeneralService.errorWrapper(
          async () => {
            return await sdk.media.getBinary(item._id);
          },
          async (value: Buffer) => {
            return value;
          }
        );

        const link = document.createElement('a');

        const blob = new Blob([buffer], { type: item.mimetype });
        const objectURL = URL.createObjectURL(blob);

        link.href = objectURL;
        link.href = URL.createObjectURL(blob);
        link.setAttribute('target', '_blank');

        if (item.size > 11572000) {
          link.download = item.name;
        }
        link.click();
      }
    }
  }
  async function getMedia(
    _media?: Media[],
    filter?: MediaFilterType
  ): Promise<MediaInView> {
    chunk = 0;
    showFilesToIndex = chunkSize + chunk * chunkSize;
    const output: MediaInView = {
      dirs: [],
      files: [],
    };
    let m: Media[] = [];
    if (_media) {
      if (mediaId) {
        m = _media.filter((e) => e.parentId === mediaId);
      } else {
        m = _media.filter((e) => e.isInRoot);
      }
    } else {
      m = await GeneralService.errorWrapper(
        async () => {
          if (filter) {
            if (
              filter.search.name.length > 2 ||
              filter.options.find((option) => {
                if (option.dropdown && option.dropdown.selected.value) {
                  return true;
                } else if (option.date && option.date.year !== -1) {
                  return true;
                }
                return false;
              })
            ) {
              return await sdk.media.getAll();
            }
          }
          if (mediaId) {
            return (await sdk.media.getAll()).filter(
              (e) => e.parentId === mediaId
            );
          }
          return (await sdk.media.getAll()).filter((e) => e.isInRoot);
        },
        async (value: Media[]) => {
          return value;
        }
      );
    }
    if (filter) {
      m = filterMedia(m, filter);
    }
    m.forEach((media) => {
      if (media.type === MediaType.DIR) {
        output.dirs.push(media);
      } else {
        output.files.push(media);
      }
    });
    return sortMedia(output);
  }
  async function createFolder(name: string, parentId?: string) {
    if (parentId === '') {
      parentId = undefined;
    }
    await GeneralService.errorWrapper(
      async () => {
        await sdk.media.addDir({
          name,
          parentId,
        });
      },
      async () => {
        mediaInView = await getMedia();
        NotificationService.success('Folder successfully created.');
      }
    );
  }
  async function remove(media: Media) {
    if (
      await ConfirmService.confirm(
        `Delete "${media.name}"`,
        `Are you sure you want to delete <strong>${media.name}</strong>?
          This action is irreversable and all child media will be also deleted.`
      )
    ) {
      await GeneralService.errorWrapper(
        async () => {
          await sdk.media.deleteById(media._id);
        },
        async () => {
          StoreService.update('media', await sdk.media.getAll());
          NotificationService.success('Media successfully removed.');
        }
      );
    }
  }
  async function preProcessFiles(files: UppyFile[]) {
    const fileNameParts = files[0].name.split('.');

    await createFiles(
      mediaId ? mediaId : '',
      GeneralService.string.toUri(
        fileNameParts.splice(0, fileNameParts.length - 1).join('.')
      ),
      files.map((e) => {
        if (e.data instanceof Blob) {
          return new File([e.data as Blob], e.name, {
            type: e.type,
          });
        }
        return e.data as File;
      })
    );
    MediaFilterActions.reset();
  }

  onMount(async () => {
    mediaInView = await getMedia();
    if (lastState.mediaId) {
      mediaId = lastState.mediaId;
    }
    if (!isItemSelect && mediaId) {
      Router.navigate(`/dashboard/media/editor/${mediaId}`, {
        replace: true,
      });
    }
  });
  beforeUpdate(async () => {
    if (buffer.mediaId !== mediaId) {
      buffer.mediaId = !mediaId ? undefined : '' + mediaId;
      lastState.mediaId = mediaId;
      mediaInView = await getMedia();
    }
  });
  onDestroy(() => {
    mediaStoreUnsub();
  });
</script>

<MediaFilter
  on:upload={() => {
    ModalService.open.mediaUploader({
      async onDone(files) {
        await preProcessFiles(files);
      },
    });
  }}
  on:reset={async (event) => {
    mediaInView = await getMedia(undefined, event.detail);
  }}
  on:filter={async (event) => {
    mediaInView = await getMedia(undefined, event.detail);
  }}
/>
<div class="view--content">
  <div class="view--content-details">
    {#if mediaId}
      <Breadcrumb
        {mediaId}
        on:open={(event) => {
          handleMediaClick({
            _id: event.detail ? event.detail : undefined,
            type: MediaType.DIR,
            createdAt: 0,
            updatedAt: 0,
            hasChildren: false,
            isInRoot: false,
            mimetype: '',
            name: '',
            parentId: '',
            path: '',
            size: 0,
            userId: '',
          });
        }}
      />
    {:else}
      <h2 class="view--title">Media manager</h2>
    {/if}
    {#if mediaInView.dirs.length > 0 || mediaInView.files.length > 0}
      <button
        on:click={() => {
          mediaInView = sortMedia(mediaInView, true);
        }}
        class="media--sort-toggler {sortData.name.direction === 1
          ? 'media--sort-toggler_asc'
          : ''}"
      >
        <span class="mr-5">Name</span>
        <ArrowUpIcon />
      </button>
    {/if}
  </div>
  {#if mediaInView.dirs.length > 0 || mediaInView.files.length > 0}
    <ul class="media--list">
      {#each mediaInView.dirs as item}
        <MediaItem
          {item}
          on:remove={() => {
            remove(item);
          }}
          on:open={() => {
            handleMediaClick(item).catch((error) => {
              console.error(error);
            });
          }}
        />
      {/each}
      {#each mediaInView.files as item, itemIndex}
        {#if itemIndex < showFilesToIndex}
          <MediaItem
            {item}
            selected={selectedItem && selectedItem._id === item._id}
            on:remove={() => {
              remove(item);
            }}
            on:open={() => {
              handleMediaClick(item).catch((error) => {
                console.error(error);
              });
            }}
          />
        {/if}
      {/each}
      {#if mediaInView.files.length > showFilesToIndex}
        <button
          class="media--item-click media--item-click_more"
          on:click={() => {
            chunk = chunk + 1;
            showFilesToIndex = chunkSize + chunk * chunkSize;
          }}>Show More</button
        >
      {/if}
    </ul>
  {:else}
    <div>
      <h3 class="media--list_empty">
        Upload your first files to see them here
      </h3>
    </div>
  {/if}
  <MediaRemoveFileModal
    on:cancel={() => {}}
    on:done={async (event) => {
      if (event.detail) {
        await GeneralService.errorWrapper(
          async () => {
            await sdk.media.deleteById(event.detail);
          },
          async () => {
            StoreService.update('media', await sdk.media.getAll());
            NotificationService.success('Media successfully removed.');
          }
        );
      }
    }}
  />
</div>
<MediaAddUpdateFolderModal
  on:done={(event) => {
    createFolder(event.detail.name, mediaId ? mediaId : '');
  }}
/>
<Spinner show={uploading.active}
  ><div class="media--upload-filename">Uploading: {uploading.fileName}</div>
  <div class="media--upload-wrapper">
    <div class="media--upload-bar" style="width: {uploading.progress}%;" />
  </div></Spinner
>

// src/components/media/viewer.vue
<script lang="tsx">
import { computed, defineComponent, onMounted, PropType, ref } from 'vue';
import type { BCMSMedia } from '@becomes/cms-sdk/types';
import { BCMSMediaType } from '@becomes/cms-sdk/types';
import BCMSMediaControls from './controls.vue';
import BCMSMediaItem from './item.vue';
import BCMSMediaBreadcrumb from './breadcrumb.vue';
import { BCMSMediaControlFilters } from '../../types';
import { MutationTypes, useStore } from '../../store';
import { useRoute, useRouter } from 'vue-router';
import BCMSIcon from '../icon.vue';
import type { UppyFile } from '@uppy/core';
import { BCMSSpinner } from '../spinner';

interface MediaInView {
  dirs: BCMSMedia[];
  files: BCMSMedia[];
}

const CHUNK_SIZE = 18;
const lastState = {
  mediaId: '',
};
async function getMedia(
  targetMediaId?: string,
  media?: BCMSMedia[],
  filters?: BCMSMediaControlFilters,
  sortDirection?: -1 | 1
): Promise<MediaInView> {
  const output: MediaInView = {
    dirs: [],
    files: [],
  };
  let m: BCMSMedia[] = [];
  if (media) {
    if (filters && filters.search.name) {
      m = media;
      if (filters.search.name) {
        m = m.filter((item) =>
          item.name
            .toLowerCase()
            .includes(filters.search.name.trim().toLowerCase())
        );
      }
    } else {
      if (targetMediaId) {
        m = media.filter((e) => e.parentId === targetMediaId);
      } else {
        m = media.filter((e) => e.isInRoot);
      }
    }
  }

  m.forEach((item) => {
    if (item.type === BCMSMediaType.DIR) {
      output.dirs.push(item);
    } else {
      output.files.push(item);
    }
  });
  return sortMedia(output, sortDirection ? sortDirection : 1);
}
function sortMedia(media: MediaInView, direction: -1 | 1): MediaInView {
  return {
    dirs: media.dirs.sort((a, b) => (a.name > b.name ? direction : -direction)),
    files: media.files.sort((a, b) =>
      a.name > b.name ? direction : -direction
    ),
  };
}

const component = defineComponent({
  props: {
    mode: {
      type: String as PropType<'view' | 'select'>,
      default: 'view',
    },
    onSelect: Function as PropType<(media: BCMSMedia) => void | Promise<void>>,
  },
  emits: {
    select: (_value: BCMSMedia) => {
      return true;
    },
  },
  setup(props, ctx) {
    const router = useRouter();
    const route = useRoute();
    const store = useStore();
    const media = computed(() => {
      return store.getters.media_items;
    });
    const mediaId = ref(lastState.mediaId);
    const mediaInView = ref<MediaInView>({
      dirs: [],
      files: [],
    });
    const filters = ref<BCMSMediaControlFilters | undefined>(undefined);
    const selectedMedia = ref<BCMSMedia | null>(null);
    const atChunk = ref(0);
    const showToIndex = computed(() => {
      return CHUNK_SIZE + atChunk.value * CHUNK_SIZE;
    });
    const sortDirection = ref<1 | -1>(1);
    const uploadSpinnerData = ref({
      active: false,
      fileName: '',
      progress: 0,
    });

    async function handleMediaClick(item: BCMSMedia) {
      if (props.mode === 'select') {
        if (item.type === BCMSMediaType.DIR) {
          mediaId.value = item._id;
          lastState.mediaId = mediaId.value;
          mediaInView.value = await getMedia(
            mediaId.value,
            media.value,
            filters.value,
            sortDirection.value
          );
        } else {
          selectedMedia.value = item;
          ctx.emit('select', item);
        }
      } else if (props.mode === 'view') {
        if (item.type === BCMSMediaType.DIR) {
          if (item._id) {
            lastState.mediaId = item._id;
            mediaId.value = item._id;
            await router.push({
              path: `/dashboard/media/${item._id}`,
              replace: true,
            });
          } else {
            lastState.mediaId = '';
            mediaId.value = '';
            await router.push({
              path: '/dashboard/media',
              replace: true,
            });
          }
          if (filters.value) {
            filters.value = filters.value.clear();
          }
          mediaInView.value = await getMedia(
            mediaId.value,
            media.value,
            filters.value,
            sortDirection.value
          );
        } else {
          const mediaLink = await window.bcms.sdk.media.getUrlWithAccessToken(
            item
          );
          window.open(
            window.location.href.split('/').slice(0, 3).join('/') + mediaLink,
            '_blank'
          );
        }
      }
    }
    async function createDir(name: string) {
      const parentId = mediaId.value ? mediaId.value : undefined;
      await window.bcms.services.error.wrapper(
        async () => {
          return await window.bcms.sdk.media.addDir({
            name,
            parentId,
          });
        },
        async (result) => {
          store.commit(MutationTypes.media_set, result);
          mediaInView.value = await getMedia(
            mediaId.value,
            media.value,
            filters.value,
            sortDirection.value
          );
        }
      );
    }
    async function removeMedia(target: BCMSMedia) {
      if (
        await window.bcms.services.confirm(
          `Delete "${target.name}"`,
          `Are you sure you want to delete <strong>${target.name}</strong>?
          This action is irreversable and all child media will be also deleted.`
        )
      ) {
        await window.bcms.services.error.wrapper(
          async () => {
            await window.bcms.sdk.media.deleteById(target._id);
          },
          async () => {
            store.commit(MutationTypes.media_remove, target);
            mediaInView.value = await getMedia(
              mediaId.value,
              media.value,
              filters.value,
              sortDirection.value
            );
            window.bcms.services.notification.success(
              'Media successfully removed.'
            );
          }
        );
      }
    }
    async function preProcessFiles(files: UppyFile[]) {
      await createFiles(
        files.map((e) => {
          if (e.data instanceof Blob) {
            return new File([e.data as Blob], e.name, {
              type: e.type,
            });
          }
          return e.data as File;
        })
      );
    }
    async function createFiles(files: File[]) {
      uploadSpinnerData.value.active = true;
      const result = await window.bcms.services.media.createFiles(
        mediaId.value,
        files,
        (event) => {
          uploadSpinnerData.value.fileName = event.fileName;
          uploadSpinnerData.value.progress = (event.loaded * 100) / event.total;
        }
      );
      if (result.errors.length > 0) {
        console.error(result.errors);
        window.bcms.services.notification.error(
          'Upload completed with errors.' +
            ' See console for more information.' +
            ' This files were not uploaded: ' +
            result.errors.map((e) => e.filename).join(', ')
        );
      } else {
        window.bcms.services.notification.success(
          'Files uploaded successfully.'
        );
      }
      store.commit(MutationTypes.media_set, result.media);
      mediaInView.value = await getMedia(
        mediaId.value,
        media.value,
        filters.value,
        sortDirection.value
      );
      uploadSpinnerData.value.active = false;
    }

    onMounted(async () => {
      if (media.value.length === 0) {
        await window.bcms.services.error.wrapper(
          async () => {
            return await window.bcms.sdk.media.getAll();
          },
          async (result) => {
            store.commit(MutationTypes.media_set, result);
          }
        );
      }
      if (route.path.startsWith('/dashboard/media')) {
        if (
          !lastState.mediaId &&
          route.params.id &&
          route.params.id !== lastState.mediaId
        ) {
          lastState.mediaId = route.params.id as string;
          mediaId.value = lastState.mediaId;
          await router.push({
            path: `/dashboard/media/${lastState.mediaId}`,
            replace: true,
          });
        } else if (
          !route.params.id &&
          lastState.mediaId &&
          route.params.id !== lastState.mediaId
        ) {
          mediaId.value = lastState.mediaId;
          await router.push({
            path: `/dashboard/media/${lastState.mediaId}`,
            replace: true,
          });
        }
      }
      mediaInView.value = await getMedia(
        mediaId.value,
        media.value,
        filters.value,
        sortDirection.value
      );
    });

    return () => (
      <>
        <BCMSMediaControls
          onUploadFile={() => {
            window.bcms.services.modal.media.upload.show({
              title: 'Upload files',
              onDone: async (data) => {
                await preProcessFiles(data.files);
              },
            });
            // ModalService.open.mediaUploader({
            //   async onDone(files) {
            //     await preProcessFiles(files);
            //   },
            // });
          }}
          onCreateFolder={() => {
            window.bcms.services.modal.media.addUpdateDir.show({
              title: 'Create new folder',
              mode: 'add',
              takenNames: mediaInView.value.dirs.map((e) => e.name),
              onDone: async (data) => {
                await createDir(data.name);
              },
            });
          }}
          onFilter={async (_filters) => {
            filters.value = _filters;
            mediaInView.value = await getMedia(
              mediaId.value,
              media.value,
              filters.value,
              sortDirection.value
            );
          }}
        />
        <div class="view--content">
          <div class="view--content-details">
            {mediaId.value ? (
              <BCMSMediaBreadcrumb
                targetMediaId={mediaId.value}
                onClick={async (data) => {
                  await handleMediaClick(data);
                }}
              />
            ) : (
              <h2 class="view--title">Media manager</h2>
            )}
            {mediaInView.value.dirs.length > 0 ||
            mediaInView.value.files.length > 0 ? (
              <button
                onClick={() => {
                  sortDirection.value = sortDirection.value === 1 ? -1 : 1;
                  mediaInView.value = sortMedia(
                    mediaInView.value,
                    sortDirection.value
                  );
                }}
                class={`media--sort-toggler ${
                  sortDirection.value === 1 ? 'media--sort-toggler_asc' : ''
                }`}
              >
                <span class="mr-5">Name</span>
                <BCMSIcon src="/arrow/up" />
              </button>
            ) : (
              ''
            )}
          </div>
          {mediaInView.value.dirs.length > 0 ||
          mediaInView.value.files.length > 0 ? (
            <ul class="media--list">
              {mediaInView.value.dirs.map((item) => {
                return (
                  <BCMSMediaItem
                    item={item}
                    onRemove={async () => {
                      await removeMedia(item);
                    }}
                    onOpen={async () => {
                      await handleMediaClick(item);
                    }}
                  />
                );
              })}
              {mediaInView.value.files.map((item, itemIndex) => {
                if (itemIndex < showToIndex.value) {
                  return (
                    <BCMSMediaItem
                      item={item}
                      selected={
                        !!selectedMedia.value &&
                        selectedMedia.value._id === item._id
                      }
                      onRemove={async () => {
                        await removeMedia(item);
                      }}
                      onOpen={async () => {
                        await handleMediaClick(item);
                      }}
                    />
                  );
                } else {
                  return <li style="display: none;" />;
                }
              })}
            </ul>
          ) : (
            <div>
              <h3 class="media--list_empty">
                Upload your first files to see them here
              </h3>
            </div>
          )}
        </div>
        <BCMSSpinner show={uploadSpinnerData.value.active}>
          <div class="media--upload-filename">
            Uploading: {uploadSpinnerData.value.fileName}
          </div>
          <div class="media--upload-wrapper">
            <div
              class="media--upload-bar"
              style={`width: ${uploadSpinnerData.value.progress}%;`}
            />
          </div>
        </BCMSSpinner>
      </>
    );
  },
});
export default component;
</script>
